#!/usr/bin/env python3
"""
Seeded generators for PlotTracer's bundled EXAMPLE figures — and, crucially, the
GROUND TRUTH they were rendered from (checkpoint 123+).

Every bundled example (samples/*.png) is a synthetic figure. Historically these
were made by ad-hoc scripts that were never committed, so the real values behind
them were lost. That is a shame twice over: the examples can't be regenerated, and
we can't tell a user "here is exactly how close your extraction was" — a self-test
/ accuracy score that doubles as a validation harness for any automated extraction
(comparing extraction against the known table of values behind a figure).

So from here on, each example is generated by a COMMITTED, SEEDED script that emits
BOTH the PNG and a `<name>.truth.json` carrying the exact values in the schema
CLAUDE.md defines (source / axes / series). Deterministic: same numpy seed +
matplotlib version -> same figure + same truth.

Dev-only tool (not a runtime dep). Requires: numpy, matplotlib, pillow.
Run:  python3 samples/generators/gen_samples.py

ALL 14 bundled examples are now banked here (ground truth complete, 2026-07-20):
the "series of values" types (scatter, xy-multiseries, bar, histogram,
categorical, xy-stress-strain — the e2e SAMPLE_IMAGE, errorbar, boxplot, polar,
ccr, dash-styles) plus the three that were deferred to last because they carry no
native matplotlib primitive or were image/PDF-backed: TERNARY (hand-built
triangle), MAP (lon/lat with a decorative landmass), and the 3-page MULTIPAGE
PDF. The ternary/map/pdf values were MEASURED off the earlier throwaway exemplars
(whose source values were lost) and replotted from those measurements (David) —
see the scratch measurement scripts' method in each generator's docstring.
"""

import json
import os

import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

SAMPLES_DIR = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
NAVY = "#1f4e79"


def _save(fig, name):
    """Save a 900x700 RGB PNG (matching every other bundled sample)."""
    png = os.path.join(SAMPLES_DIR, name + ".png")
    fig.savefig(png, facecolor="white")
    plt.close(fig)
    # Force RGB (matplotlib writes RGBA); every other sample is RGB.
    from PIL import Image

    Image.open(png).convert("RGB").save(png)


def _write_truth(name, truth):
    with open(os.path.join(SAMPLES_DIR, name + ".truth.json"), "w") as f:
        json.dump(truth, f, indent=2)


def gen_scatter():
    """Compressive modulus vs. crosslinker concentration — 26 separated markers
    (rejection-sampled so none touch -> the Blob Detector finds exactly one
    centroid per marker). Byte-reproduces the checkpoint-123 sample."""
    name = "scatter-crosslink-modulus"
    rng = np.random.default_rng(7)
    XMAX, YMAX = 10.0, 120.0
    PX_PER_X, PX_PER_Y, MIN_SEP_PX = 77.0, 4.75, 20.0
    pts, attempts = [], 0
    while len(pts) < 26 and attempts < 20000:
        attempts += 1
        x = rng.uniform(0.5, 9.5)
        y = 12 + 9.5 * x + rng.normal(0, 7)
        if not (5 <= y <= 115):
            continue
        if all(((x - px) * PX_PER_X) ** 2 + ((y - py) * PX_PER_Y) ** 2 >= MIN_SEP_PX ** 2 for px, py in pts):
            pts.append((x, y))
    pts.sort()
    xs = np.array([p[0] for p in pts])
    ys = np.array([p[1] for p in pts])

    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax.scatter(xs, ys, s=60, c=NAVY, edgecolors="none", zorder=3)
    ax.set_xlim(0, XMAX)
    ax.set_ylim(0, YMAX)
    ax.set_xlabel("Crosslinker concentration (mol%)", fontsize=13)
    ax.set_ylabel("Compressive modulus (kPa)", fontsize=13)
    ax.set_title("Compressive modulus vs. crosslinker concentration", fontsize=15)
    ax.grid(True, color="#dddddd", linewidth=0.8, zorder=0)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — the exact values the figure was rendered from. For a self-test / accuracy score."},
        "graphType": "xy",
        "axes": {"x": {"label": "Crosslinker concentration (mol%)", "min": 0, "max": 10},
                 "y": {"label": "Compressive modulus (kPa)", "min": 0, "max": 120}},
        "series": [{"name": "modulus", "points": [{"x": round(float(a), 4), "y": round(float(b), 3)} for a, b in zip(xs, ys)]}],
    })


def gen_multiseries():
    """Storage modulus vs. temperature for 4 biopolymer blends — 4 line series,
    each ~9 plotted data points. Truth = each series' vertices."""
    name = "xy-multiseries-modulus"
    rng = np.random.default_rng(11)
    x = np.linspace(20, 100, 9)
    blends = [
        ("Blend A", NAVY, 3200, -22),
        ("Blend B", "#c0392b", 2600, -18),
        ("Blend C", "#27ae60", 2000, -14),
        ("Blend D", "#8e44ad", 1500, -10),
    ]
    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    series = []
    for label, color, y0, slope in blends:
        # A softening curve: high modulus that rolls off with temperature.
        y = y0 + slope * (x - 20) + rng.normal(0, 30, x.size)
        y = np.clip(y, 50, None)
        ax.plot(x, y, "-o", color=color, markersize=5, linewidth=1.8, label=label)
        series.append({"name": label, "points": [{"x": round(float(a), 2), "y": round(float(b), 2)} for a, b in zip(x, y)]})
    ax.set_xlim(0, 110)
    ax.set_ylim(0, 3600)
    ax.set_xlabel("Temperature (°C)", fontsize=13)
    ax.set_ylabel("Storage modulus (MPa)", fontsize=13)
    ax.set_title("Storage modulus vs. temperature — 4 blends", fontsize=15)
    ax.grid(True, color="#dddddd", linewidth=0.8)
    ax.legend(fontsize=10)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — exact vertices of each plotted line."},
        "graphType": "xy",
        "axes": {"x": {"label": "Temperature (°C)", "min": 0, "max": 110},
                 "y": {"label": "Storage modulus (MPa)", "min": 0, "max": 3600}},
        "series": series,
    })


def gen_bar():
    """Tensile strength across fibre types — categorical bars. Truth = per-bar
    value."""
    name = "bar-tensile-strength"
    cats = ["Flax", "Hemp", "Jute", "Kenaf", "Sisal", "Ramie"]
    vals = [345, 285, 210, 190, 165, 400]
    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax.bar(cats, vals, color=NAVY, width=0.6)
    # Grid BEHIND the bars: matplotlib's default axisbelow='line' draws the grid
    # over filled patches, which striped each bar with white gridlines (David).
    ax.set_axisbelow(True)
    ax.set_ylim(0, 450)
    ax.set_ylabel("Tensile strength (MPa)", fontsize=13)
    ax.set_title("Tensile strength by fibre type", fontsize=15)
    ax.grid(True, axis="y", color="#dddddd", linewidth=0.8)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — per-bar value."},
        "graphType": "bar",
        "axes": {"y": {"label": "Tensile strength (MPa)", "min": 0, "max": 450}},
        "series": [{"name": "tensile strength", "points": [{"category": c, "value": v} for c, v in zip(cats, vals)]}],
    })


def gen_histogram():
    """Pore-size distribution — a histogram over uniform bins. Truth = each bin's
    edges and count (the record PlotTracer captures as true bin intervals)."""
    name = "histogram-pore-size"
    edges = np.arange(0, 110, 10)  # 0..100 in 10 bins
    counts = [4, 11, 23, 38, 52, 41, 27, 15, 7, 2]
    centers = (edges[:-1] + edges[1:]) / 2
    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax.bar(centers, counts, width=9.2, color=NAVY, align="center")
    ax.set_axisbelow(True)  # grid behind the bars, not striping them (David)
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 60)
    ax.set_xlabel("Pore diameter (µm)", fontsize=13)
    ax.set_ylabel("Count", fontsize=13)
    ax.set_title("Pore-size distribution", fontsize=15)
    ax.grid(True, axis="y", color="#dddddd", linewidth=0.8)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — true bin edges + count."},
        "graphType": "histogram",
        "axes": {"x": {"label": "Pore diameter (µm)", "min": 0, "max": 100},
                 "y": {"label": "Count", "min": 0, "max": 60}},
        "series": [{"name": "pore size", "points": [
            {"binStart": int(edges[i]), "binEnd": int(edges[i + 1]), "value": int(counts[i])} for i in range(len(counts))]}],
    })


def gen_categorical():
    """Young's modulus across discrete fibre categories, drawn as a LINE over a
    categorical X (the type ckpt 101 added). Truth = per-category value; X has no
    numeric meaning, only order."""
    name = "categorical-fibre-modulus"
    cats = ["Untreated", "Alkali", "Silane", "Acetyl", "Enzyme"]
    vals = [18.5, 24.2, 29.8, 27.1, 22.6]
    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax.plot(cats, vals, "-o", color=NAVY, markersize=7, linewidth=2)
    ax.set_ylim(0, 35)
    ax.set_ylabel("Young's modulus (GPa)", fontsize=13)
    ax.set_title("Fibre modulus by surface treatment", fontsize=15)
    ax.grid(True, axis="y", color="#dddddd", linewidth=0.8)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — per-category value; X is ordered, not numeric."},
        "graphType": "categorical",
        "axes": {"y": {"label": "Young's modulus (GPa)", "min": 0, "max": 35}},
        "series": [{"name": "modulus", "points": [{"category": c, "value": v} for c, v in zip(cats, vals)]}],
    })


def gen_stress_strain():
    """A tensile stress–strain curve (a flagship materials-testing extraction case):
    elastic rise → yield → strain hardening → a gentle post-peak decline. Navy so
    the colour-trace e2e (target #1f4e79) still matches; drawn thick so the
    segment-fill flood has a solid line to follow. Truth = a dense sampling of the
    curve (a continuous curve's ground truth is the curve itself)."""
    name = "xy-stress-strain"
    x = np.linspace(0, 15, 400)  # strain %
    # Piecewise-smooth: Hookean rise, rounded yield ~3%, hardening, decline past ~11%.
    stress = 42 * np.tanh(x / 3.2) + 0.9 * x - 0.09 * np.clip(x - 11, 0, None) ** 2
    stress = np.clip(stress, 0, None)

    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax.plot(x, stress, color=NAVY, linewidth=2.6, solid_capstyle="round")
    ax.set_xlim(0, 15)
    ax.set_ylim(0, 50)
    ax.set_xlabel("Strain (%)", fontsize=13)
    ax.set_ylabel("Stress (MPa)", fontsize=13)
    ax.set_title("Tensile stress–strain curve", fontsize=15)
    ax.grid(True, color="#dddddd", linewidth=0.8)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    _save(fig, name)
    # Dense truth: 61 evenly-spaced samples along the curve (enough to score a
    # trace against without storing all 400 render points).
    xs = np.linspace(0, 15, 61)
    ys = np.clip(42 * np.tanh(xs / 3.2) + 0.9 * xs - 0.09 * np.clip(xs - 11, 0, None) ** 2, 0, None)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — a dense sampling of the plotted curve (continuous: the truth is the curve)."},
        "graphType": "xy",
        "axes": {"x": {"label": "Strain (%)", "min": 0, "max": 15},
                 "y": {"label": "Stress (MPa)", "min": 0, "max": 50}},
        "series": [{"name": "stress", "points": [{"x": round(float(a), 3), "y": round(float(b), 3)} for a, b in zip(xs, ys)]}],
    })


def gen_errorbar():
    """Tensile strength vs. cure time WITH error bars (the flagship uncertainty
    case). Truth = each point's value and its absolute upper/lower cap — the
    schema ckpt 70/79 record (deltas derived, never stored)."""
    name = "errorbar-tensile-cure"
    x = np.array([5, 10, 20, 40, 60, 90, 120], dtype=float)  # cure time (min)
    y = np.array([8, 18, 31, 42, 47, 49, 50], dtype=float)   # tensile strength (MPa)
    sd = np.array([1.5, 2.2, 3.0, 2.6, 2.1, 1.8, 1.6])       # ± SD
    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax.errorbar(x, y, yerr=sd, fmt="o", color=NAVY, ecolor=NAVY, elinewidth=1.6, capsize=5, markersize=6)
    ax.set_xlim(0, 130)
    ax.set_ylim(0, 60)
    ax.set_xlabel("Cure time (min)", fontsize=13)
    ax.set_ylabel("Tensile strength (MPa)", fontsize=13)
    ax.set_title("Tensile strength vs. cure time (± SD)", fontsize=15)
    ax.grid(True, color="#dddddd", linewidth=0.8)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — value + absolute upper/lower cap per point (deltas are derived)."},
        "graphType": "xy",
        "axes": {"x": {"label": "Cure time (min)", "min": 0, "max": 130},
                 "y": {"label": "Tensile strength (MPa)", "min": 0, "max": 60}},
        "series": [{"name": "tensile strength", "points": [
            {"x": float(a), "y": float(b), "yUpper": round(float(b + s), 3), "yLower": round(float(b - s), 3)}
            for a, b, s in zip(x, y, sd)]}],
    })


def gen_boxplot():
    """Tensile strength distribution by fibre type, as box plots drawn from
    KNOWN five-number summaries (ax.bxp takes precomputed stats -> the truth is
    exact). Truth = per-box min/Q1/median/Q3/max."""
    name = "bar-box-plot-tensile-strength"
    boxes = [
        ("Flax", 250, 300, 340, 380, 420),
        ("Hemp", 200, 250, 285, 315, 360),
        ("Jute", 150, 185, 210, 235, 270),
        ("Kenaf", 130, 165, 190, 215, 250),
        ("Sisal", 110, 145, 165, 190, 220),
    ]
    stats = [{"label": c, "whislo": lo, "q1": q1, "med": md, "q3": q3, "whishi": hi, "fliers": []}
             for c, lo, q1, md, q3, hi in boxes]
    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    bp = ax.bxp(stats, showfliers=False, patch_artist=True, medianprops={"color": "#c0392b", "linewidth": 2})
    ax.set_axisbelow(True)  # grid behind the boxes, not striping them (David)
    for box in bp["boxes"]:
        box.set(facecolor="#d6e0ec", edgecolor=NAVY)
    for w in bp["whiskers"] + bp["caps"]:
        w.set(color=NAVY)
    ax.set_ylim(0, 450)
    ax.set_ylabel("Tensile strength (MPa)", fontsize=13)
    ax.set_title("Tensile strength distribution by fibre type", fontsize=15)
    ax.grid(True, axis="y", color="#dddddd", linewidth=0.8)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — five-number summary per box."},
        "graphType": "boxplot",
        "axes": {"y": {"label": "Tensile strength (MPa)", "min": 0, "max": 450}},
        "series": [{"name": "tensile strength", "points": [
            {"category": c, "min": lo, "q1": q1, "median": md, "q3": q3, "max": hi} for c, lo, q1, md, q3, hi in boxes]}],
    })


def gen_polar():
    """Diffusion rate vs. angle — a polar plot. Truth = (angle°, radius) samples."""
    name = "polar-diffusion-rate"
    theta = np.linspace(0, 2 * np.pi, 24, endpoint=False)
    r = 6 + 3 * np.cos(theta - 0.6) + 0.5 * np.cos(3 * theta)  # a lobed diffusion profile
    fig = plt.figure(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax = fig.add_subplot(projection="polar")
    tc = np.append(theta, theta[0])
    rc = np.append(r, r[0])
    ax.plot(tc, rc, "-o", color=NAVY, markersize=4, linewidth=1.8)
    ax.set_rmax(10)
    ax.set_title("Diffusion rate vs. angle (µm²/s)", fontsize=15)
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — (angle°, radius) samples."},
        "graphType": "polar",
        "axes": {"angle": {"label": "Angle", "min": 0, "max": 360, "unit": "deg"},
                 "radius": {"label": "Diffusion rate (µm²/s)", "min": 0, "max": 10}},
        "series": [{"name": "diffusion", "points": [
            {"angle": round(float(np.degrees(t)), 2), "radius": round(float(rr), 3)} for t, rr in zip(theta, r)]}],
    })


def gen_ccr():
    """Circular chart recorder — temperature over a 24 h rotation (time mapped to
    angle, value to radius). Truth = (time h, temperature °C) samples."""
    name = "circular-temperature-recording"
    hours = np.arange(0, 24, 1.0)
    theta = hours / 24.0 * 2 * np.pi
    temp = 21 + 4 * np.sin((hours - 8) / 24 * 2 * np.pi) + 0.6 * np.sin(hours / 3.0)  # daily cycle
    fig = plt.figure(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax = fig.add_subplot(projection="polar")
    ax.set_theta_zero_location("N")
    ax.set_theta_direction(-1)  # clockwise, like a chart recorder
    tc = np.append(theta, theta[0])
    rc = np.append(temp, temp[0])
    ax.plot(tc, rc, "-", color=NAVY, linewidth=1.8)
    ax.set_rmin(0)
    ax.set_rmax(30)
    # Label the dial in HOURS, not degrees — a chart recorder's angular axis is
    # time (one 24 h rotation), which is what the CCR calibration reads. 0 h at
    # the top (N), clockwise. This makes the time->angle mapping self-evident.
    ax.set_thetagrids(list(range(0, 360, 30)), labels=[f"{int(a / 360 * 24)} h" for a in range(0, 360, 30)])
    ax.set_title("24 h temperature recording (°C)", fontsize=15)
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — (time h, temperature C) samples; time maps to angle over one 24 h rotation. Calibrate with a time-format start (e.g. 0:00) and rotation = day, direction = clockwise, so the extracted Time reads back as a clock time rather than a raw number."},
        "graphType": "ccr",
        "axes": {"time": {"label": "Time", "min": 0, "max": 24, "unit": "h"},
                 "radius": {"label": "Temperature (°C)", "min": 0, "max": 30}},
        "series": [{"name": "temperature", "points": [
            {"time": float(h), "value": round(float(t), 3)} for h, t in zip(hours, temp)]}],
    })


def gen_dashstyles():
    """A black-and-white technical drawing whose curves are distinguished ONLY by
    DASH STYLE — solid / dashed / dash-dot / dotted — all drawn in the SAME black
    (v0.8, David). This is the motivating case for Interpolation-assist: you can't
    colour-separate same-colour curves (Auto-trace by colour is useless here), and
    a dashed line has no unbroken path for Segment Fill's flood to follow — so the
    intended workflow is drop a few guide points on the dashed curve you're
    following and let the spline fill between them. Four cumulative-release curves
    (first-order kinetics), staggered so they stay separable across the range.
    Truth = a dense sampling of each curve (continuous: the truth is the curve)."""
    name = "xy-dashed-release"
    BLACK = "#111111"
    # (label, matplotlib linestyle, Rmax %, rate k /h)
    curves = [
        ("Formulation A", "-", 96.0, 0.85),
        ("Formulation B", "--", 88.0, 0.48),
        ("Formulation C", "-.", 78.0, 0.30),
        ("Formulation D", ":", 66.0, 0.18),
    ]
    x = np.linspace(0, 12, 300)  # time (h)

    def release(rmax, k, t):
        return rmax * (1.0 - np.exp(-k * t))

    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    series = []
    for label, ls, rmax, k in curves:
        y = release(rmax, k, x)
        ax.plot(x, y, linestyle=ls, color=BLACK, linewidth=1.9, label=label)
        # Dense truth: 49 evenly-spaced samples along each curve.
        xs = np.linspace(0, 12, 49)
        ys = release(rmax, k, xs)
        series.append({"name": label, "points": [
            {"x": round(float(a), 3), "y": round(float(b), 3)} for a, b in zip(xs, ys)]})
    ax.set_xlim(0, 12)
    ax.set_ylim(0, 100)
    ax.set_xlabel("Time (h)", fontsize=13)
    ax.set_ylabel("Cumulative release (%)", fontsize=13)
    ax.set_title("Cumulative release — 4 formulations (dash-coded)", fontsize=15)
    # Faint grid only; the figure is otherwise pure black-on-white so the sole
    # cue distinguishing the four curves is the dash pattern.
    ax.grid(True, color="#dddddd", linewidth=0.8)
    ax.legend(fontsize=10, loc="lower right")
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — dense sampling of each dash-coded curve (monochrome; curves differ ONLY by dash style)."},
        "graphType": "xy",
        "axes": {"x": {"label": "Time (h)", "min": 0, "max": 12},
                 "y": {"label": "Cumulative release (%)", "min": 0, "max": 100}},
        "series": series,
    })


def gen_ternary():
    """Ternary blend composition — biopolymer films (chitosan / alginate /
    cellulose, summing to 100%). matplotlib has no native ternary axes, so the
    triangle is hand-built (upward: top=Chitosan, bottom-left=Alginate,
    bottom-right=Cellulose, 20% grid). The 6 blend compositions were MEASURED off
    the previous throwaway exemplar (whose values were lost) and replotted from
    there (David, 2026-07-20) — they came back as clean round numbers, so those
    are what the original figure encoded. Truth = per-blend (a, b, c) = the three
    corner values; keys match the app's ternary a/b/c labels, vertex roles noted."""
    name = "ternary-blend-composition"
    # (label, a=Chitosan[top], b=Alginate[bottom-left], c=Cellulose[bottom-right])
    blends = [
        ("Blend 1", 70, 20, 10),
        ("Blend 2", 50, 30, 20),
        ("Blend 3", 40, 10, 50),
        ("Blend 4", 33, 33, 34),
        ("Blend 5", 20, 50, 30),
        ("Blend 6", 15, 15, 70),
    ]
    h = np.sqrt(3) / 2.0
    T, L, Rr = np.array([0.5, h]), np.array([0.0, 0.0]), np.array([1.0, 0.0])

    def bary(a, b, c):  # percentages -> triangle xy (a=top, b=left, c=right)
        f = np.array([a, b, c], float) / 100.0
        return f[0] * T + f[1] * L + f[2] * Rr

    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    # Triangle outline.
    tri = np.array([L, Rr, T, L])
    ax.plot(tri[:, 0], tri[:, 1], color="black", linewidth=1.6, zorder=2)
    # 20% grid: three families of lines parallel to each edge.
    for t in (20, 40, 60, 80):
        f = t / 100.0
        # constant-a (parallel to base), constant-b, constant-c
        ax.plot(*zip(bary(t, 100 - t, 0), bary(t, 0, 100 - t)), color="#e2e2e2", lw=0.8, zorder=1)
        ax.plot(*zip(bary(0, t, 100 - t), bary(100 - t, t, 0)), color="#e2e2e2", lw=0.8, zorder=1)
        ax.plot(*zip(bary(100 - t, 0, t), bary(0, 100 - t, t)), color="#e2e2e2", lw=0.8, zorder=1)
    for _, a, b, c in blends:
        p = bary(a, b, c)
        ax.plot(p[0], p[1], "o", markersize=10, markerfacecolor="#3a9d5d", markeredgecolor="#1c5a32", markeredgewidth=1.2, zorder=3)
    # Corner labels carry an A/B/C calibration marker in the ORDER the app's
    # ternary math needs the corners clicked (bottom-left -> bottom-right -> top;
    # verified: this winding yields all-positive components summing to 100). So
    # A=bottom-left=Alginate, B=bottom-right=Cellulose, C=top=Chitosan, and the
    # app's a/b/c come out as Alginate/Cellulose/Chitosan.
    ax.text(T[0], T[1] + 0.03, "C · Chitosan (%)", ha="center", va="bottom", fontsize=12, color="#5a3a2a", fontweight="bold")
    ax.text(L[0] - 0.02, L[1] - 0.03, "A · Alginate (%)", ha="center", va="top", fontsize=12, color="#5a3a2a", fontweight="bold")
    ax.text(Rr[0] + 0.02, Rr[1] - 0.03, "B · Cellulose (%)", ha="center", va="top", fontsize=12, color="#5a3a2a", fontweight="bold")
    ax.set_title("Ternary Blend Composition — Biopolymer Films", fontsize=15, fontweight="bold")
    ax.set_xlim(-0.12, 1.12)
    ax.set_ylim(-0.12, h + 0.12)
    ax.set_aspect("equal")
    ax.axis("off")
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth. a/b/c follow the app's ternary calibration order A->B->C = bottom-left(Alginate) -> bottom-right(Cellulose) -> top(Chitosan)."},
        "graphType": "ternary",
        "axes": {"a": {"label": "Alginate (%)", "vertex": "bottom-left", "corner": "A"},
                 "b": {"label": "Cellulose (%)", "vertex": "bottom-right", "corner": "B"},
                 "c": {"label": "Chitosan (%)", "vertex": "top", "corner": "C"}},
        # tuple order is (Chitosan a_top, Alginate b_left, Cellulose c_right); the
        # app's a/b/c are (Alginate, Cellulose, Chitosan) = (b, c, a).
        "series": [{"name": "blends", "points": [{"a": b, "b": c, "c": a} for _, a, b, c in blends]}],
    })


def gen_map():
    """Field-survey map with a SCALE BAR — the Map axes type is a *scale-bar*
    model (uniform distance/pixel from a corner origin), NOT gridded x/y axes. So
    this figure has a 200 km scale bar and no numeric axes: you place the two
    calibration points on the bar, pick a corner as origin, and every feature
    reads out in km from that corner.

    The axes fill the whole figure edge-to-edge (add_axes([0,0,1,1]) + equal
    aspect), so the image's bottom-left pixel IS the (0,0) origin and a site's
    "km from corner" equals its plotted km position -> truth = each site's
    (x_km, y_km). A green landmass polygon is decoration; the record is the
    sites."""
    name = "map-collection-sites"
    W, H = 1000.0, 800.0  # km extent; origin (0,0) at the image's bottom-left
    sites = [("Site A", 180, 130), ("Site B", 470, 300), ("Site C", 700, 560), ("Site D", 860, 470)]
    land = [(70, 250), (170, 470), (280, 430), (430, 560), (560, 600), (700, 520),
            (840, 630), (910, 430), (760, 300), (520, 250), (180, 160)]

    fig = plt.figure(figsize=(W / 100, H / 100), dpi=100)
    fig.patch.set_facecolor("white")
    ax = fig.add_axes([0, 0, 1, 1])  # fill the figure: image corner == (0,0) km
    ax.set_xlim(0, W)
    ax.set_ylim(0, H)
    ax.set_aspect("equal")  # square pixels — the Map model's uniform-scale assumption
    ax.set_facecolor("#eef4fb")  # sea
    ax.add_patch(plt.Polygon(land, closed=True, facecolor="#d7e8c9", edgecolor="#8fae74", linewidth=1.6, zorder=1))
    for label, x, y in sites:
        ax.plot(x, y, "o", markersize=11, markerfacecolor="#d9463e", markeredgecolor="#7a2019", markeredgewidth=1.2, zorder=3)
        ax.annotate(f"  {label}", (x, y), fontsize=13, va="center", zorder=4)
    # Scale bar: a 200 km reference with end caps + label (the calibration target).
    sx, sy, slen = 90, 70, 200.0
    ax.plot([sx, sx + slen], [sy, sy], color="black", linewidth=3, zorder=5)
    for xx in (sx, sx + slen):
        ax.plot([xx, xx], [sy - 12, sy + 12], color="black", linewidth=3, zorder=5)
    ax.text(sx + slen / 2, sy + 20, "200 km", ha="center", va="bottom", fontsize=13, fontweight="bold", zorder=5)
    ax.text(W / 2, H - 30, "Sample Collection Sites — Field Survey Map", ha="center", va="top", fontsize=16, fontweight="bold", zorder=5)
    ax.set_xticks([])
    ax.set_yticks([])
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — each site's (x, y) in km from the bottom-left corner (the Map origin). Calibrate on the 200 km scale bar with origin = bottom-left; the axes fill the image so the corner is (0,0). The landmass is decoration."},
        "graphType": "map",
        "axes": {"scaleBar": {"length": 200, "unit": "km"}, "origin": "bottom-left",
                 "x": {"label": "Easting", "min": 0, "max": W, "unit": "km"},
                 "y": {"label": "Northing", "min": 0, "max": H, "unit": "km"}},
        "series": [{"name": "collection sites", "points": [{"name": s, "x": float(x), "y": float(y)} for s, x, y in sites]}],
    })


def gen_multipage_pdf():
    """A 3-page PDF, one figure per page — the multi-figure showcase (checkpoint
    114). Each page's data was MEASURED off the previous throwaway PDF and
    replotted (David, 2026-07-20): (1) a PLA/flax tensile stress–strain curve
    (XY), (2) tensile strength by fibre (bar), (3) flexural modulus by fibre (a
    line over a categorical X). Truth = one entry per page/figure, each in its own
    graph type's schema."""
    from matplotlib.backends.backend_pdf import PdfPages

    name = "multipage-figures"
    ss_x = [0, 2, 4, 5, 7, 9, 11, 15, 19, 22.5]
    ss_y = [0, 24, 40, 43, 44, 43.5, 44, 48, 54, 58]
    bar_cats = ["Flax", "Hemp", "Jute", "Kenaf", "Sisal"]
    bar_vals = [58, 52, 46, 41, 35]
    flex_cats = ["Flax", "Hemp", "Jute", "Kenaf", "Sisal", "Coir"]
    flex_vals = [8.2, 7.5, 6.8, 5.9, 5.1, 3.4]

    pdf_path = os.path.join(SAMPLES_DIR, name + ".pdf")
    with PdfPages(pdf_path) as pdf:
        # Page 1 — XY stress–strain.
        fig = plt.figure(figsize=(8.5, 11), dpi=100)
        ax = fig.add_axes([0.13, 0.56, 0.78, 0.35])
        ax.plot(ss_x, ss_y, "-o", color=NAVY, markersize=4, linewidth=1.5)
        ax.set_xlim(0, 25); ax.set_ylim(0, 60)
        ax.set_xlabel("Strain (%)"); ax.set_ylabel("Stress (MPa)")
        ax.set_title("Tensile Stress-Strain - PLA/Flax", fontweight="bold")
        ax.grid(True, color="#dddddd", linewidth=0.8)
        fig.text(0.13, 0.45, "Figure 1.  Tensile stress-strain response of a PLA-flax composite. The curve shows an\ninitial elastic region, yield near 5% strain, and\nductile failure past the ultimate stress.", fontsize=11)
        pdf.savefig(fig); plt.close(fig)

        # Page 2 — bar.
        fig = plt.figure(figsize=(8.5, 11), dpi=100)
        ax = fig.add_axes([0.13, 0.56, 0.78, 0.35])
        ax.bar(bar_cats, bar_vals, color=NAVY, width=0.6)
        ax.set_axisbelow(True)
        ax.set_ylim(0, 70)
        ax.set_xlabel("Fibre type"); ax.set_ylabel("Tensile strength (MPa)")
        ax.set_title("Tensile Strength by Fibre", fontweight="bold")
        ax.grid(True, axis="y", color="#dddddd", linewidth=0.8)
        fig.text(0.13, 0.45, "Figure 2.  Ultimate tensile strength of composites reinforced with different natural\nfibres. Error bars omitted for clarity.", fontsize=11)
        pdf.savefig(fig); plt.close(fig)

        # Page 3 — categorical line.
        fig = plt.figure(figsize=(8.5, 11), dpi=100)
        ax = fig.add_axes([0.13, 0.56, 0.78, 0.35])
        ax.plot(flex_cats, flex_vals, "-o", color=NAVY, markersize=5, linewidth=1.6)
        ax.set_ylim(0, 10)
        ax.set_xlabel("Fibre type"); ax.set_ylabel("Flexural modulus (GPa)")
        ax.set_title("Flexural Modulus by Fibre", fontweight="bold")
        ax.grid(True, color="#dddddd", linewidth=0.8)
        fig.text(0.13, 0.45, "Figure 3.  Flexural modulus across fibre types, plotted as a line to emphasise the\nmonotonic trend (the x axis is categorical, not numeric).", fontsize=11)
        pdf.savefig(fig); plt.close(fig)

    _write_truth(name, {
        "source": {"imagePath": name + ".pdf", "note": "Synthetic ground truth — one figure per page (measured off the prior exemplar, replotted). Each page is its own graph type."},
        "figures": [
            {"page": 1, "graphType": "xy",
             "axes": {"x": {"label": "Strain (%)", "min": 0, "max": 25}, "y": {"label": "Stress (MPa)", "min": 0, "max": 60}},
             "series": [{"name": "PLA/Flax", "points": [{"x": float(a), "y": float(b)} for a, b in zip(ss_x, ss_y)]}]},
            {"page": 2, "graphType": "bar",
             "axes": {"y": {"label": "Tensile strength (MPa)", "min": 0, "max": 70}},
             "series": [{"name": "tensile strength", "points": [{"category": c, "value": v} for c, v in zip(bar_cats, bar_vals)]}]},
            {"page": 3, "graphType": "categorical",
             "axes": {"y": {"label": "Flexural modulus (GPa)", "min": 0, "max": 10}},
             "series": [{"name": "flexural modulus", "points": [{"category": c, "value": v} for c, v in zip(flex_cats, flex_vals)]}]},
        ],
    })


if __name__ == "__main__":
    gen_scatter()
    gen_multiseries()
    gen_bar()
    gen_histogram()
    gen_categorical()
    gen_stress_strain()
    gen_errorbar()
    gen_boxplot()
    gen_polar()
    gen_ccr()
    gen_dashstyles()
    gen_ternary()
    gen_map()
    gen_multipage_pdf()
    print("generated all 14 examples (+ .truth.json each): 11 PNG series types, ternary, map, multipage-pdf.")
