#!/usr/bin/env python3
"""
Seeded generators for PlotTracer's bundled EXAMPLE figures — and, crucially, the
GROUND TRUTH they were rendered from (checkpoint 123+).

Every bundled example (samples/*.png) is a synthetic figure. Historically these
were made by ad-hoc scripts that were never committed, so the real values behind
them were lost. That is a shame twice over: the examples can't be regenerated, and
we can't tell a user "here is exactly how close your extraction was" — a self-test
/ accuracy score that doubles as a validation harness for any automated extraction
(comparing extraction against the known table of values behind a figure).

So from here on, each example is generated by a COMMITTED, SEEDED script that emits
BOTH the PNG and a `<name>.truth.json` carrying the exact values in the schema
CLAUDE.md defines (source / axes / series). Deterministic: same numpy seed +
matplotlib version -> same figure + same truth.

Dev-only tool (not a runtime dep). Requires: numpy, matplotlib, pillow.
Run:  python3 samples/generators/gen_samples.py

ALL 14 bundled examples are now banked here (ground truth complete, 2026-07-20):
the "series of values" types (scatter, xy-multiseries, bar, histogram,
categorical, xy-stress-strain — the e2e SAMPLE_IMAGE, errorbar, boxplot, polar,
ccr, dash-styles) plus the three that were deferred to last because they carry no
native matplotlib primitive or were image/PDF-backed: TERNARY (hand-built
triangle), MAP (lon/lat with a decorative landmass), and the 3-page MULTIPAGE
PDF. The ternary/map/pdf values were MEASURED off the earlier throwaway exemplars
(whose source values were lost) and replotted from those measurements (David) —
see the scratch measurement scripts' method in each generator's docstring.
"""

import json
import math
import os

import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

SAMPLES_DIR = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
NAVY = "#1f4e79"


def _save(fig, name):
    """Save a 900x700 RGB PNG (matching every other bundled sample).

    Set env SKIP_PNG=1 to re-emit only the .truth.json (e.g. to add the
    `calibration` block) WITHOUT rewriting the committed PNG — so a truth-only
    change can't drift the bundled images across matplotlib versions."""
    if os.environ.get("SKIP_PNG") == "1":
        plt.close(fig)
        return
    png = os.path.join(SAMPLES_DIR, name + ".png")
    fig.savefig(png, facecolor="white")
    plt.close(fig)
    # Force RGB (matplotlib writes RGBA); every other sample is RGB.
    from PIL import Image

    Image.open(png).convert("RGB").save(png)


def _write_truth(name, truth):
    with open(os.path.join(SAMPLES_DIR, name + ".truth.json"), "w") as f:
        json.dump(truth, f, indent=2)


def _xy_calibration(fig, ax, xmin, xmax, ymin, ymax):
    """The 4 XY calibration anchors (x1/x2/y1/y2) in IMAGE/canvas pixel space —
    origin top-left, y DOWN — which is the space PlotTracer's calibration uses.

    This lets the Trace Challenge game PRE-CALIBRATE a round (the player only
    places points, never clicks the axes). `ax.transData` maps data -> display
    pixels (origin bottom-left, y UP) at the figure's dpi, which equals the saved
    900x700 PNG, so we y-flip to canvas coords. x1/y1 share the (xmin,ymin) corner
    pixel, matching the app's standard shared-origin calibration handle."""
    fig.canvas.draw()  # finalise the layout (post tight_layout) so transData is exact
    h = fig.get_figheight() * fig.dpi
    w = fig.get_figwidth() * fig.dpi

    def anchor(dx, dy, value):
        sx, sy = ax.transData.transform((dx, dy))
        return {"px": round(float(sx), 2), "py": round(float(h - sy), 2), "value": value}

    return {
        "imageWidth": round(w),
        "imageHeight": round(h),
        "anchors": {
            "x1": anchor(xmin, ymin, xmin),
            "x2": anchor(xmax, ymin, xmax),
            "y1": anchor(xmin, ymin, ymin),
            "y2": anchor(xmin, ymax, ymax),
        },
    }


def _value_calibration(fig, ax, vmin, vmax):
    """The 2 value-axis calibration anchors (p1/p2) for Bar / Box-plot, which
    calibrate ONLY the magnitude axis (no category/x calibration). Image-pixel
    space, y-flipped — same conventions as _xy_calibration. The px is taken on the
    left axis edge; only py carries the value mapping (vertical bars)."""
    fig.canvas.draw()
    h = fig.get_figheight() * fig.dpi
    w = fig.get_figwidth() * fig.dpi
    x0 = ax.get_xlim()[0]

    def anchor(value):
        sx, sy = ax.transData.transform((x0, value))
        return {"px": round(float(sx), 2), "py": round(float(h - sy), 2), "value": value}

    return {
        "imageWidth": round(w),
        "imageHeight": round(h),
        "anchors": {"p1": anchor(vmin), "p2": anchor(vmax)},
    }


def gen_scatter():
    """Compressive modulus vs. crosslinker concentration — 26 separated markers
    (rejection-sampled so none touch -> the Blob Detector finds exactly one
    centroid per marker). Byte-reproduces the checkpoint-123 sample."""
    name = "scatter-crosslink-modulus"
    rng = np.random.default_rng(7)
    XMAX, YMAX = 10.0, 120.0
    PX_PER_X, PX_PER_Y, MIN_SEP_PX = 77.0, 4.75, 20.0
    pts, attempts = [], 0
    while len(pts) < 26 and attempts < 20000:
        attempts += 1
        x = rng.uniform(0.5, 9.5)
        y = 12 + 9.5 * x + rng.normal(0, 7)
        if not (5 <= y <= 115):
            continue
        if all(((x - px) * PX_PER_X) ** 2 + ((y - py) * PX_PER_Y) ** 2 >= MIN_SEP_PX ** 2 for px, py in pts):
            pts.append((x, y))
    pts.sort()
    xs = np.array([p[0] for p in pts])
    ys = np.array([p[1] for p in pts])

    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax.scatter(xs, ys, s=60, c=NAVY, edgecolors="none", zorder=3)
    ax.set_xlim(0, XMAX)
    ax.set_ylim(0, YMAX)
    ax.set_xlabel("Crosslinker concentration (mol%)", fontsize=13)
    ax.set_ylabel("Compressive modulus (kPa)", fontsize=13)
    ax.set_title("Compressive modulus vs. crosslinker concentration", fontsize=15)
    ax.grid(True, color="#dddddd", linewidth=0.8, zorder=0)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    calib = _xy_calibration(fig, ax, 0, XMAX, 0, YMAX)
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — the exact values the figure was rendered from. For a self-test / accuracy score."},
        "graphType": "xy",
        "axes": {"x": {"label": "Crosslinker concentration (mol%)", "min": 0, "max": 10},
                 "y": {"label": "Compressive modulus (kPa)", "min": 0, "max": 120}},
        "calibration": calib,
        "series": [{"name": "modulus", "points": [{"x": round(float(a), 4), "y": round(float(b), 3)} for a, b in zip(xs, ys)]}],
    })


def gen_multiseries():
    """Storage modulus vs. temperature for 4 biopolymer blends — 4 line series,
    each ~9 plotted data points. Truth = each series' vertices."""
    name = "xy-multiseries-modulus"
    rng = np.random.default_rng(11)
    x = np.linspace(20, 100, 9)
    blends = [
        ("Blend A", NAVY, 3200, -22),
        ("Blend B", "#c0392b", 2600, -18),
        ("Blend C", "#27ae60", 2000, -14),
        ("Blend D", "#8e44ad", 1500, -10),
    ]
    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    series = []
    for label, color, y0, slope in blends:
        # A softening curve: high modulus that rolls off with temperature.
        y = y0 + slope * (x - 20) + rng.normal(0, 30, x.size)
        y = np.clip(y, 50, None)
        ax.plot(x, y, "-o", color=color, markersize=5, linewidth=1.8, label=label)
        series.append({"name": label, "points": [{"x": round(float(a), 2), "y": round(float(b), 2)} for a, b in zip(x, y)]})
    ax.set_xlim(0, 110)
    ax.set_ylim(0, 3600)
    ax.set_xlabel("Temperature (°C)", fontsize=13)
    ax.set_ylabel("Storage modulus (MPa)", fontsize=13)
    ax.set_title("Storage modulus vs. temperature — 4 blends", fontsize=15)
    ax.grid(True, color="#dddddd", linewidth=0.8)
    ax.legend(fontsize=10)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    calib = _xy_calibration(fig, ax, 0, 110, 0, 3600)
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — exact vertices of each plotted line."},
        "graphType": "xy",
        "axes": {"x": {"label": "Temperature (°C)", "min": 0, "max": 110},
                 "y": {"label": "Storage modulus (MPa)", "min": 0, "max": 3600}},
        "calibration": calib,
        "series": series,
    })


def gen_bar():
    """Tensile strength across fibre types — categorical bars. Truth = per-bar
    value."""
    name = "bar-tensile-strength"
    cats = ["Flax", "Hemp", "Jute", "Kenaf", "Sisal", "Ramie"]
    vals = [345, 285, 210, 190, 165, 400]
    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax.bar(cats, vals, color=NAVY, width=0.6)
    # Grid BEHIND the bars: matplotlib's default axisbelow='line' draws the grid
    # over filled patches, which striped each bar with white gridlines (David).
    ax.set_axisbelow(True)
    ax.set_ylim(0, 450)
    ax.set_ylabel("Tensile strength (MPa)", fontsize=13)
    ax.set_title("Tensile strength by fibre type", fontsize=15)
    ax.grid(True, axis="y", color="#dddddd", linewidth=0.8)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    calib = _value_calibration(fig, ax, 0, 450)
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — per-bar value."},
        "graphType": "bar",
        "axes": {"y": {"label": "Tensile strength (MPa)", "min": 0, "max": 450}},
        "calibration": calib,
        "series": [{"name": "tensile strength", "points": [{"category": c, "value": v} for c, v in zip(cats, vals)]}],
    })


def gen_bar_grouped():
    """Cell viability, control vs. treatment — a GROUPED bar (v2.0): two series
    sharing one category axis, side by side per category rather than stacked.
    Truth = per-bar value, one entry per series, same shape as gen_bar's single
    series repeated -- a grouped bar has no shared-baseline arithmetic to get
    wrong, unlike a stacked one."""
    name = "bar-grouped-viability"
    cats = ["Day 3", "Day 7", "Day 14", "Day 21"]
    control = [12, 18, 22, 25]
    treatment = [12, 28, 45, 58]
    x = np.arange(len(cats))
    width = 0.35
    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax.bar(x - width / 2, control, width, color=NAVY, label="Control")
    ax.bar(x + width / 2, treatment, width, color="#c0392b", label="Treatment")
    ax.set_axisbelow(True)
    ax.set_xticks(x)
    ax.set_xticklabels(cats)
    ax.set_ylim(0, 70)
    ax.set_ylabel("Cell viability (%)", fontsize=13)
    ax.set_title("Cell viability — control vs. treatment", fontsize=15)
    ax.grid(True, axis="y", color="#dddddd", linewidth=0.8)
    ax.legend(fontsize=10)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    calib = _value_calibration(fig, ax, 0, 70)
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — per-bar value, one series per group."},
        "graphType": "bar",
        "axes": {"y": {"label": "Cell viability (%)", "min": 0, "max": 70}},
        "calibration": calib,
        "series": [
            {"name": "Control", "points": [{"category": c, "value": v} for c, v in zip(cats, control)]},
            {"name": "Treatment", "points": [{"category": c, "value": v} for c, v in zip(cats, treatment)]},
        ],
    })


def gen_bar_stacked():
    """Quarterly cost breakdown — a STACKED bar (v2.0): four series drawn as
    segments of one bar per quarter. Truth = each series' own SEGMENT height
    (its SPAN), never the cumulative top it visually reaches -- matching the
    capture model (v2.0 design): each segment is its own honestly-dragged box,
    not a shared-baseline reading. Summing a category's segments reproduces the
    bar's visual total, but that sum is a derived check, not the record."""
    name = "bar-stacked-cost"
    cats = ["Q1", "Q2", "Q3", "Q4"]
    layers = [
        ("Materials", "#1f4e79", [120, 130, 125, 140]),
        ("Labor", "#5fb4e0", [90, 95, 100, 98]),
        ("Overhead", "#e0a458", [40, 42, 38, 45]),
        ("Shipping", "#8e44ad", [20, 25, 22, 28]),
    ]
    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    bottom = np.zeros(len(cats))
    for label, color, vals in layers:
        ax.bar(cats, vals, bottom=bottom, color=color, width=0.6, label=label)
        bottom += np.array(vals, dtype=float)
    ax.set_axisbelow(True)
    ax.set_ylim(0, 360)
    ax.set_ylabel("Cost (k$)", fontsize=13)
    ax.set_title("Quarterly cost breakdown", fontsize=15)
    ax.grid(True, axis="y", color="#dddddd", linewidth=0.8)
    ax.legend(fontsize=10)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    calib = _value_calibration(fig, ax, 0, 360)
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png",
                   "note": "Synthetic ground truth -- each series' own SEGMENT height, not the cumulative stack top."},
        "graphType": "bar",
        "axes": {"y": {"label": "Cost (k$)", "min": 0, "max": 360}},
        "calibration": calib,
        "series": [{"name": label, "points": [{"category": c, "value": v} for c, v in zip(cats, vals)]} for label, _, vals in layers],
    })


def gen_bar_floating():
    """Monthly temperature range — a FLOATING bar (v2.0): neither end is the
    chart's baseline (zero), and several bars cross zero entirely. Truth =
    each bar's two measured ENDS (start/end), not a single value -- a floating
    bar has no baseline-relative magnitude to reduce to, which is exactly the
    shape the two-corner drag-box capture exists for."""
    name = "bar-floating-temperature"
    cats = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    lows = [-8, -6, -2, 3, 8, 13, 15, 14, 9, 3, -3, -7]
    highs = [2, 4, 9, 15, 20, 25, 28, 27, 21, 14, 6, 1]
    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    heights = [h - l for l, h in zip(lows, highs)]
    ax.bar(cats, heights, bottom=lows, color=NAVY, width=0.6)
    ax.axhline(0, color="#666666", linewidth=1.2, zorder=1)
    ax.set_axisbelow(True)
    ax.set_ylim(-15, 32)
    ax.set_ylabel("Temperature (°C)", fontsize=13)
    ax.set_title("Monthly temperature range", fontsize=15)
    ax.grid(True, axis="y", color="#dddddd", linewidth=0.8)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    calib = _value_calibration(fig, ax, -15, 32)
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png",
                   "note": "Synthetic ground truth -- each bar's two measured ends (low/high), never a single baseline-relative value."},
        "graphType": "bar",
        "axes": {"y": {"label": "Temperature (°C)", "min": -15, "max": 32}},
        "calibration": calib,
        "series": [{"name": "temperature range",
                    "points": [{"category": c, "start": lo, "end": hi} for c, lo, hi in zip(cats, lows, highs)]}],
    })


def gen_histogram():
    """Pore-size distribution — a histogram over uniform bins. Truth = each bin's
    edges and count (the record PlotTracer captures as true bin intervals)."""
    name = "histogram-pore-size"
    edges = np.arange(0, 110, 10)  # 0..100 in 10 bins
    counts = [4, 11, 23, 38, 52, 41, 27, 15, 7, 2]
    centers = (edges[:-1] + edges[1:]) / 2
    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax.bar(centers, counts, width=9.2, color=NAVY, align="center")
    ax.set_axisbelow(True)  # grid behind the bars, not striping them (David)
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 60)
    ax.set_xlabel("Pore diameter (µm)", fontsize=13)
    ax.set_ylabel("Count", fontsize=13)
    ax.set_title("Pore-size distribution", fontsize=15)
    ax.grid(True, axis="y", color="#dddddd", linewidth=0.8)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    calib = _xy_calibration(fig, ax, 0, 100, 0, 60)
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — true bin edges + count."},
        "graphType": "histogram",
        "axes": {"x": {"label": "Pore diameter (µm)", "min": 0, "max": 100},
                 "y": {"label": "Count", "min": 0, "max": 60}},
        "calibration": calib,
        "series": [{"name": "pore size", "points": [
            {"binStart": int(edges[i]), "binEnd": int(edges[i + 1]), "value": int(counts[i])} for i in range(len(counts))]}],
    })


def gen_categorical():
    """Young's modulus across discrete fibre categories, drawn as a LINE over a
    categorical X (the type ckpt 101 added). Truth = per-category value; X has no
    numeric meaning, only order."""
    name = "categorical-fibre-modulus"
    cats = ["Untreated", "Alkali", "Silane", "Acetyl", "Enzyme"]
    vals = [18.5, 24.2, 29.8, 27.1, 22.6]
    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax.plot(cats, vals, "-o", color=NAVY, markersize=7, linewidth=2)
    ax.set_ylim(0, 35)
    ax.set_ylabel("Young's modulus (GPa)", fontsize=13)
    ax.set_title("Fibre modulus by surface treatment", fontsize=15)
    ax.grid(True, axis="y", color="#dddddd", linewidth=0.8)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — per-category value; X is ordered, not numeric."},
        "graphType": "categorical",
        "axes": {"y": {"label": "Young's modulus (GPa)", "min": 0, "max": 35}},
        "series": [{"name": "modulus", "points": [{"category": c, "value": v} for c, v in zip(cats, vals)]}],
    })


def gen_stress_strain():
    """A tensile stress–strain curve (a flagship materials-testing extraction case):
    elastic rise → yield → strain hardening → a gentle post-peak decline. Navy so
    the colour-trace e2e (target #1f4e79) still matches; drawn thick so the
    segment-fill flood has a solid line to follow. Truth = a dense sampling of the
    curve (a continuous curve's ground truth is the curve itself)."""
    name = "xy-stress-strain"
    x = np.linspace(0, 15, 400)  # strain %
    # Piecewise-smooth: Hookean rise, rounded yield ~3%, hardening, decline past ~11%.
    stress = 42 * np.tanh(x / 3.2) + 0.9 * x - 0.09 * np.clip(x - 11, 0, None) ** 2
    stress = np.clip(stress, 0, None)

    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax.plot(x, stress, color=NAVY, linewidth=2.6, solid_capstyle="round")
    ax.set_xlim(0, 15)
    ax.set_ylim(0, 50)
    ax.set_xlabel("Strain (%)", fontsize=13)
    ax.set_ylabel("Stress (MPa)", fontsize=13)
    ax.set_title("Tensile stress–strain curve", fontsize=15)
    ax.grid(True, color="#dddddd", linewidth=0.8)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    calib = _xy_calibration(fig, ax, 0, 15, 0, 50)
    _save(fig, name)
    # Dense truth: 61 evenly-spaced samples along the curve (enough to score a
    # trace against without storing all 400 render points).
    xs = np.linspace(0, 15, 61)
    ys = np.clip(42 * np.tanh(xs / 3.2) + 0.9 * xs - 0.09 * np.clip(xs - 11, 0, None) ** 2, 0, None)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — a dense sampling of the plotted curve (continuous: the truth is the curve)."},
        "graphType": "xy",
        "axes": {"x": {"label": "Strain (%)", "min": 0, "max": 15},
                 "y": {"label": "Stress (MPa)", "min": 0, "max": 50}},
        "calibration": calib,
        "series": [{"name": "stress", "points": [{"x": round(float(a), 3), "y": round(float(b), 3)} for a, b in zip(xs, ys)]}],
    })


def gen_errorbar():
    """Tensile strength vs. cure time WITH error bars (the flagship uncertainty
    case). Truth = each point's value and its absolute upper/lower cap — the
    schema ckpt 70/79 record (deltas derived, never stored)."""
    name = "errorbar-tensile-cure"
    x = np.array([5, 10, 20, 40, 60, 90, 120], dtype=float)  # cure time (min)
    y = np.array([8, 18, 31, 42, 47, 49, 50], dtype=float)   # tensile strength (MPa)
    sd = np.array([1.5, 2.2, 3.0, 2.6, 2.1, 1.8, 1.6])       # ± SD
    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax.errorbar(x, y, yerr=sd, fmt="o", color=NAVY, ecolor=NAVY, elinewidth=1.6, capsize=5, markersize=6)
    ax.set_xlim(0, 130)
    ax.set_ylim(0, 60)
    ax.set_xlabel("Cure time (min)", fontsize=13)
    ax.set_ylabel("Tensile strength (MPa)", fontsize=13)
    ax.set_title("Tensile strength vs. cure time (± SD)", fontsize=15)
    ax.grid(True, color="#dddddd", linewidth=0.8)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — value + absolute upper/lower cap per point (deltas are derived)."},
        "graphType": "xy",
        "axes": {"x": {"label": "Cure time (min)", "min": 0, "max": 130},
                 "y": {"label": "Tensile strength (MPa)", "min": 0, "max": 60}},
        "series": [{"name": "tensile strength", "points": [
            {"x": float(a), "y": float(b), "yUpper": round(float(b + s), 3), "yLower": round(float(b - s), 3)}
            for a, b, s in zip(x, y, sd)]}],
    })


def gen_boxplot():
    """Tensile strength distribution by fibre type, as box plots drawn from
    KNOWN five-number summaries (ax.bxp takes precomputed stats -> the truth is
    exact). Truth = per-box min/Q1/median/Q3/max."""
    name = "bar-box-plot-tensile-strength"
    boxes = [
        ("Flax", 250, 300, 340, 380, 420),
        ("Hemp", 200, 250, 285, 315, 360),
        ("Jute", 150, 185, 210, 235, 270),
        ("Kenaf", 130, 165, 190, 215, 250),
        ("Sisal", 110, 145, 165, 190, 220),
    ]
    stats = [{"label": c, "whislo": lo, "q1": q1, "med": md, "q3": q3, "whishi": hi, "fliers": []}
             for c, lo, q1, md, q3, hi in boxes]
    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    bp = ax.bxp(stats, showfliers=False, patch_artist=True, medianprops={"color": "#c0392b", "linewidth": 2})
    ax.set_axisbelow(True)  # grid behind the boxes, not striping them (David)
    for box in bp["boxes"]:
        box.set(facecolor="#d6e0ec", edgecolor=NAVY)
    for w in bp["whiskers"] + bp["caps"]:
        w.set(color=NAVY)
    ax.set_ylim(0, 450)
    ax.set_ylabel("Tensile strength (MPa)", fontsize=13)
    ax.set_title("Tensile strength distribution by fibre type", fontsize=15)
    ax.grid(True, axis="y", color="#dddddd", linewidth=0.8)
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    calib = _value_calibration(fig, ax, 0, 450)
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — five-number summary per box."},
        "graphType": "boxplot",
        "axes": {"y": {"label": "Tensile strength (MPa)", "min": 0, "max": 450}},
        "calibration": calib,
        "series": [{"name": "tensile strength", "points": [
            {"category": c, "min": lo, "q1": q1, "median": md, "q3": q3, "max": hi} for c, lo, q1, md, q3, hi in boxes]}],
    })


def gen_polar():
    """Diffusion rate vs. angle — a polar plot. Truth = (angle°, radius) samples."""
    name = "polar-diffusion-rate"
    theta = np.linspace(0, 2 * np.pi, 24, endpoint=False)
    r = 6 + 3 * np.cos(theta - 0.6) + 0.5 * np.cos(3 * theta)  # a lobed diffusion profile
    fig = plt.figure(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax = fig.add_subplot(projection="polar")
    tc = np.append(theta, theta[0])
    rc = np.append(r, r[0])
    ax.plot(tc, rc, "-o", color=NAVY, markersize=4, linewidth=1.8)
    ax.set_rmax(10)
    ax.set_title("Diffusion rate vs. angle (µm²/s)", fontsize=15)
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — (angle°, radius) samples."},
        "graphType": "polar",
        "axes": {"angle": {"label": "Angle", "min": 0, "max": 360, "unit": "deg"},
                 "radius": {"label": "Diffusion rate (µm²/s)", "min": 0, "max": 10}},
        "series": [{"name": "diffusion", "points": [
            {"angle": round(float(np.degrees(t)), 2), "radius": round(float(rr), 3)} for t, rr in zip(theta, r)]}],
    })


def gen_ccr():
    """Circular chart recorder — temperature over a 24 h rotation (time mapped to
    angle, value to radius). Truth = (time h, temperature °C) samples."""
    name = "circular-temperature-recording"
    hours = np.arange(0, 24, 1.0)
    theta = hours / 24.0 * 2 * np.pi
    temp = 21 + 4 * np.sin((hours - 8) / 24 * 2 * np.pi) + 0.6 * np.sin(hours / 3.0)  # daily cycle
    fig = plt.figure(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax = fig.add_subplot(projection="polar")
    ax.set_theta_zero_location("N")
    ax.set_theta_direction(-1)  # clockwise, like a chart recorder
    tc = np.append(theta, theta[0])
    rc = np.append(temp, temp[0])
    ax.plot(tc, rc, "-", color=NAVY, linewidth=1.8)
    ax.set_rmin(0)
    ax.set_rmax(30)
    # Label the dial in HOURS, not degrees — a chart recorder's angular axis is
    # time (one 24 h rotation), which is what the CCR calibration reads. 0 h at
    # the top (N), clockwise. This makes the time->angle mapping self-evident.
    ax.set_thetagrids(list(range(0, 360, 30)), labels=[f"{int(a / 360 * 24)} h" for a in range(0, 360, 30)])
    ax.set_title("24 h temperature recording (°C)", fontsize=15)
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — (time h, temperature C) samples; time maps to angle over one 24 h rotation. Calibrate with a time-format start (e.g. 0:00) and rotation = day, direction = clockwise, so the extracted Time reads back as a clock time rather than a raw number."},
        "graphType": "ccr",
        "axes": {"time": {"label": "Time", "min": 0, "max": 24, "unit": "h"},
                 "radius": {"label": "Temperature (°C)", "min": 0, "max": 30}},
        "series": [{"name": "temperature", "points": [
            {"time": float(h), "value": round(float(t), 3)} for h, t in zip(hours, temp)]}],
    })


def gen_dashstyles():
    """A black-and-white technical drawing whose curves are distinguished ONLY by
    DASH STYLE — solid / dashed / dash-dot / dotted — all drawn in the SAME black
    (v0.8, David). This is the motivating case for Interpolation-assist: you can't
    colour-separate same-colour curves (Auto-trace by colour is useless here), and
    a dashed line has no unbroken path for Segment Fill's flood to follow — so the
    intended workflow is drop a few guide points on the dashed curve you're
    following and let the spline fill between them. Four cumulative-release curves
    (first-order kinetics), staggered so they stay separable across the range.
    Truth = a dense sampling of each curve (continuous: the truth is the curve)."""
    name = "xy-dashed-release"
    BLACK = "#111111"
    # (label, matplotlib linestyle, Rmax %, rate k /h)
    curves = [
        ("Formulation A", "-", 96.0, 0.85),
        ("Formulation B", "--", 88.0, 0.48),
        ("Formulation C", "-.", 78.0, 0.30),
        ("Formulation D", ":", 66.0, 0.18),
    ]
    x = np.linspace(0, 12, 300)  # time (h)

    def release(rmax, k, t):
        return rmax * (1.0 - np.exp(-k * t))

    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    series = []
    for label, ls, rmax, k in curves:
        y = release(rmax, k, x)
        ax.plot(x, y, linestyle=ls, color=BLACK, linewidth=1.9, label=label)
        # Dense truth: 49 evenly-spaced samples along each curve.
        xs = np.linspace(0, 12, 49)
        ys = release(rmax, k, xs)
        series.append({"name": label, "points": [
            {"x": round(float(a), 3), "y": round(float(b), 3)} for a, b in zip(xs, ys)]})
    ax.set_xlim(0, 12)
    ax.set_ylim(0, 100)
    ax.set_xlabel("Time (h)", fontsize=13)
    ax.set_ylabel("Cumulative release (%)", fontsize=13)
    ax.set_title("Cumulative release — 4 formulations (dash-coded)", fontsize=15)
    # Faint grid only; the figure is otherwise pure black-on-white so the sole
    # cue distinguishing the four curves is the dash pattern.
    ax.grid(True, color="#dddddd", linewidth=0.8)
    ax.legend(fontsize=10, loc="lower right")
    ax.tick_params(labelsize=11)
    fig.tight_layout()
    calib = _xy_calibration(fig, ax, 0, 12, 0, 100)
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — dense sampling of each dash-coded curve (monochrome; curves differ ONLY by dash style)."},
        "graphType": "xy",
        "axes": {"x": {"label": "Time (h)", "min": 0, "max": 12},
                 "y": {"label": "Cumulative release (%)", "min": 0, "max": 100}},
        "calibration": calib,
        "series": series,
    })


def gen_ternary():
    """Ternary blend composition — biopolymer films (chitosan / alginate /
    cellulose, summing to 100%). matplotlib has no native ternary axes, so the
    triangle is hand-built (upward: top=Chitosan, bottom-left=Alginate,
    bottom-right=Cellulose, 20% grid). The 6 blend compositions were MEASURED off
    the previous throwaway exemplar (whose values were lost) and replotted from
    there (David, 2026-07-20) — they came back as clean round numbers, so those
    are what the original figure encoded. Truth = per-blend (a, b, c) = the three
    corner values; keys match the app's ternary a/b/c labels, vertex roles noted."""
    name = "ternary-blend-composition"
    # (label, a=Chitosan[top], b=Alginate[bottom-left], c=Cellulose[bottom-right])
    blends = [
        ("Blend 1", 70, 20, 10),
        ("Blend 2", 50, 30, 20),
        ("Blend 3", 40, 10, 50),
        ("Blend 4", 33, 33, 34),
        ("Blend 5", 20, 50, 30),
        ("Blend 6", 15, 15, 70),
    ]
    h = np.sqrt(3) / 2.0
    T, L, Rr = np.array([0.5, h]), np.array([0.0, 0.0]), np.array([1.0, 0.0])

    def bary(a, b, c):  # percentages -> triangle xy (a=top, b=left, c=right)
        f = np.array([a, b, c], float) / 100.0
        return f[0] * T + f[1] * L + f[2] * Rr

    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    # Triangle outline.
    tri = np.array([L, Rr, T, L])
    ax.plot(tri[:, 0], tri[:, 1], color="black", linewidth=1.6, zorder=2)
    # 20% grid: three families of lines parallel to each edge.
    for t in (20, 40, 60, 80):
        f = t / 100.0
        # constant-a (parallel to base), constant-b, constant-c
        ax.plot(*zip(bary(t, 100 - t, 0), bary(t, 0, 100 - t)), color="#e2e2e2", lw=0.8, zorder=1)
        ax.plot(*zip(bary(0, t, 100 - t), bary(100 - t, t, 0)), color="#e2e2e2", lw=0.8, zorder=1)
        ax.plot(*zip(bary(100 - t, 0, t), bary(0, 100 - t, t)), color="#e2e2e2", lw=0.8, zorder=1)
    for _, a, b, c in blends:
        p = bary(a, b, c)
        ax.plot(p[0], p[1], "o", markersize=10, markerfacecolor="#3a9d5d", markeredgecolor="#1c5a32", markeredgewidth=1.2, zorder=3)
    # Corner labels carry an A/B/C calibration marker in the ORDER the app's
    # ternary math needs the corners clicked (bottom-left -> bottom-right -> top;
    # verified: this winding yields all-positive components summing to 100). So
    # A=bottom-left=Alginate, B=bottom-right=Cellulose, C=top=Chitosan, and the
    # app's a/b/c come out as Alginate/Cellulose/Chitosan.
    ax.text(T[0], T[1] + 0.03, "C · Chitosan (%)", ha="center", va="bottom", fontsize=12, color="#5a3a2a", fontweight="bold")
    ax.text(L[0] - 0.02, L[1] - 0.03, "A · Alginate (%)", ha="center", va="top", fontsize=12, color="#5a3a2a", fontweight="bold")
    ax.text(Rr[0] + 0.02, Rr[1] - 0.03, "B · Cellulose (%)", ha="center", va="top", fontsize=12, color="#5a3a2a", fontweight="bold")
    ax.set_title("Ternary Blend Composition — Biopolymer Films", fontsize=15, fontweight="bold")
    ax.set_xlim(-0.12, 1.12)
    ax.set_ylim(-0.12, h + 0.12)
    ax.set_aspect("equal")
    ax.axis("off")
    fig.tight_layout()
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth. a/b/c follow the app's ternary calibration order A->B->C = bottom-left(Alginate) -> bottom-right(Cellulose) -> top(Chitosan)."},
        "graphType": "ternary",
        "axes": {"a": {"label": "Alginate (%)", "vertex": "bottom-left", "corner": "A"},
                 "b": {"label": "Cellulose (%)", "vertex": "bottom-right", "corner": "B"},
                 "c": {"label": "Chitosan (%)", "vertex": "top", "corner": "C"}},
        # tuple order is (Chitosan a_top, Alginate b_left, Cellulose c_right); the
        # app's a/b/c are (Alginate, Cellulose, Chitosan) = (b, c, a).
        "series": [{"name": "blends", "points": [{"a": b, "b": c, "c": a} for _, a, b, c in blends]}],
    })


def gen_map():
    """Field-survey map with a SCALE BAR — the Map axes type is a *scale-bar*
    model (uniform distance/pixel from a corner origin), NOT gridded x/y axes. So
    this figure has a 200 km scale bar and no numeric axes: you place the two
    calibration points on the bar, pick a corner as origin, and every feature
    reads out in km from that corner.

    The axes fill the whole figure edge-to-edge (add_axes([0,0,1,1]) + equal
    aspect), so the image's bottom-left pixel IS the (0,0) origin and a site's
    "km from corner" equals its plotted km position -> truth = each site's
    (x_km, y_km). A green landmass polygon is decoration; the record is the
    sites."""
    name = "map-collection-sites"
    W, H = 1000.0, 800.0  # km extent; origin (0,0) at the image's bottom-left
    sites = [("Site A", 180, 130), ("Site B", 470, 300), ("Site C", 700, 560), ("Site D", 860, 470)]
    land = [(70, 250), (170, 470), (280, 430), (430, 560), (560, 600), (700, 520),
            (840, 630), (910, 430), (760, 300), (520, 250), (180, 160)]

    fig = plt.figure(figsize=(W / 100, H / 100), dpi=100)
    fig.patch.set_facecolor("white")
    ax = fig.add_axes([0, 0, 1, 1])  # fill the figure: image corner == (0,0) km
    ax.set_xlim(0, W)
    ax.set_ylim(0, H)
    ax.set_aspect("equal")  # square pixels — the Map model's uniform-scale assumption
    ax.set_facecolor("#eef4fb")  # sea
    ax.add_patch(plt.Polygon(land, closed=True, facecolor="#d7e8c9", edgecolor="#8fae74", linewidth=1.6, zorder=1))
    for label, x, y in sites:
        ax.plot(x, y, "o", markersize=11, markerfacecolor="#d9463e", markeredgecolor="#7a2019", markeredgewidth=1.2, zorder=3)
        ax.annotate(f"  {label}", (x, y), fontsize=13, va="center", zorder=4)
    # Scale bar: a 200 km reference with end caps + label (the calibration target).
    sx, sy, slen = 90, 70, 200.0
    ax.plot([sx, sx + slen], [sy, sy], color="black", linewidth=3, zorder=5)
    for xx in (sx, sx + slen):
        ax.plot([xx, xx], [sy - 12, sy + 12], color="black", linewidth=3, zorder=5)
    ax.text(sx + slen / 2, sy + 20, "200 km", ha="center", va="bottom", fontsize=13, fontweight="bold", zorder=5)
    ax.text(W / 2, H - 30, "Sample Collection Sites — Field Survey Map", ha="center", va="top", fontsize=16, fontweight="bold", zorder=5)
    ax.set_xticks([])
    ax.set_yticks([])
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png", "note": "Synthetic ground truth — each site's (x, y) in km from the bottom-left corner (the Map origin). Calibrate on the 200 km scale bar with origin = bottom-left; the axes fill the image so the corner is (0,0). The landmass is decoration."},
        "graphType": "map",
        "axes": {"scaleBar": {"length": 200, "unit": "km"}, "origin": "bottom-left",
                 "x": {"label": "Easting", "min": 0, "max": W, "unit": "km"},
                 "y": {"label": "Northing", "min": 0, "max": H, "unit": "km"}},
        "series": [{"name": "collection sites", "points": [{"name": s, "x": float(x), "y": float(y)} for s, x, y in sites]}],
    })


def gen_multipage_pdf():
    """A 3-page PDF, one figure per page — the multi-figure showcase (checkpoint
    114). Each page's data was MEASURED off the previous throwaway PDF and
    replotted (David, 2026-07-20): (1) a PLA/flax tensile stress–strain curve
    (XY), (2) tensile strength by fibre (bar), (3) flexural modulus by fibre (a
    line over a categorical X). Truth = one entry per page/figure, each in its own
    graph type's schema."""
    from matplotlib.backends.backend_pdf import PdfPages

    name = "multipage-figures"
    ss_x = [0, 2, 4, 5, 7, 9, 11, 15, 19, 22.5]
    ss_y = [0, 24, 40, 43, 44, 43.5, 44, 48, 54, 58]
    bar_cats = ["Flax", "Hemp", "Jute", "Kenaf", "Sisal"]
    bar_vals = [58, 52, 46, 41, 35]
    flex_cats = ["Flax", "Hemp", "Jute", "Kenaf", "Sisal", "Coir"]
    flex_vals = [8.2, 7.5, 6.8, 5.9, 5.1, 3.4]

    pdf_path = os.path.join(SAMPLES_DIR, name + ".pdf")
    with PdfPages(pdf_path) as pdf:
        # Page 1 — XY stress–strain.
        fig = plt.figure(figsize=(8.5, 11), dpi=100)
        ax = fig.add_axes([0.13, 0.56, 0.78, 0.35])
        ax.plot(ss_x, ss_y, "-o", color=NAVY, markersize=4, linewidth=1.5)
        ax.set_xlim(0, 25); ax.set_ylim(0, 60)
        ax.set_xlabel("Strain (%)"); ax.set_ylabel("Stress (MPa)")
        ax.set_title("Tensile Stress-Strain - PLA/Flax", fontweight="bold")
        ax.grid(True, color="#dddddd", linewidth=0.8)
        fig.text(0.13, 0.45, "Figure 1.  Tensile stress-strain response of a PLA-flax composite. The curve shows an\ninitial elastic region, yield near 5% strain, and\nductile failure past the ultimate stress.", fontsize=11)
        pdf.savefig(fig); plt.close(fig)

        # Page 2 — bar.
        fig = plt.figure(figsize=(8.5, 11), dpi=100)
        ax = fig.add_axes([0.13, 0.56, 0.78, 0.35])
        ax.bar(bar_cats, bar_vals, color=NAVY, width=0.6)
        ax.set_axisbelow(True)
        ax.set_ylim(0, 70)
        ax.set_xlabel("Fibre type"); ax.set_ylabel("Tensile strength (MPa)")
        ax.set_title("Tensile Strength by Fibre", fontweight="bold")
        ax.grid(True, axis="y", color="#dddddd", linewidth=0.8)
        fig.text(0.13, 0.45, "Figure 2.  Ultimate tensile strength of composites reinforced with different natural\nfibres. Error bars omitted for clarity.", fontsize=11)
        pdf.savefig(fig); plt.close(fig)

        # Page 3 — categorical line.
        fig = plt.figure(figsize=(8.5, 11), dpi=100)
        ax = fig.add_axes([0.13, 0.56, 0.78, 0.35])
        ax.plot(flex_cats, flex_vals, "-o", color=NAVY, markersize=5, linewidth=1.6)
        ax.set_ylim(0, 10)
        ax.set_xlabel("Fibre type"); ax.set_ylabel("Flexural modulus (GPa)")
        ax.set_title("Flexural Modulus by Fibre", fontweight="bold")
        ax.grid(True, color="#dddddd", linewidth=0.8)
        fig.text(0.13, 0.45, "Figure 3.  Flexural modulus across fibre types, plotted as a line to emphasise the\nmonotonic trend (the x axis is categorical, not numeric).", fontsize=11)
        pdf.savefig(fig); plt.close(fig)

    _write_truth(name, {
        "source": {"imagePath": name + ".pdf", "note": "Synthetic ground truth — one figure per page (measured off the prior exemplar, replotted). Each page is its own graph type."},
        "figures": [
            {"page": 1, "graphType": "xy",
             "axes": {"x": {"label": "Strain (%)", "min": 0, "max": 25}, "y": {"label": "Stress (MPa)", "min": 0, "max": 60}},
             "series": [{"name": "PLA/Flax", "points": [{"x": float(a), "y": float(b)} for a, b in zip(ss_x, ss_y)]}]},
            {"page": 2, "graphType": "bar",
             "axes": {"y": {"label": "Tensile strength (MPa)", "min": 0, "max": 70}},
             "series": [{"name": "tensile strength", "points": [{"category": c, "value": v} for c, v in zip(bar_cats, bar_vals)]}]},
            {"page": 3, "graphType": "categorical",
             "axes": {"y": {"label": "Flexural modulus (GPa)", "min": 0, "max": 10}},
             "series": [{"name": "flexural modulus", "points": [{"category": c, "value": v} for c, v in zip(flex_cats, flex_vals)]}]},
        ],
    })


def gen_spider():
    """Spider / radar — material performance profile, three biopolymer films
    (v1.4).

    Hand-built like the ternary: matplotlib's polar axes assume ONE radial scale,
    and the whole point of this figure is that each spoke carries its own.

    Three deliberate properties, each chosen to exercise what the app claims:

    1. **PER-AXIS RANGES.** Tensile runs 0-120 MPa beside a cost index running
       0-5. This is the case the only prior art (ChartSense, CHI 2017) excludes by
       assuming all axes share a scale, and it is what placing a known point on
       every spoke buys. A figure with one shared range would not test anything.
    2. **A COMMON CENTRE OF 0**, which is the rule in real spider charts and what
       the app asks for once and stores per axis.
    3. **LINE-ONLY POLYGONS, three distinct colours.** Filled overlapping radar
       polygons BLEND into new colours where they cross, which is the hard-won
       detail ChartSense reports breaking their hue clustering; an unfilled figure
       avoids it entirely and keeps every vertex clickable, which is what a
       digitizer's example should show. Vertices are marked because the vertex --
       where the shape crosses the axis -- IS the datum the user clicks.

    Truth = per series, one {axis, name, value} per spoke, matching the app's
    `Axis, Name, Value` export.
    """
    name = "spider-material-profile"
    # (axis name, max at the outer end of the spoke). Centre is 0 on every axis.
    axes_def = [
        ("Tensile strength (MPa)", 120),
        ("Elongation at break (%)", 60),
        ("Water-vapour barrier (a.u.)", 25),
        ("Transparency (%)", 100),
        ("Biodegradation (%/30 d)", 80),
        ("Cost index", 5),
    ]
    series = [
        ("Chitosan film", "#1f4e79", [92, 18, 21, 88, 46, 3.4], "o"),
        ("Alginate film", "#c1553b", [58, 41, 12, 72, 71, 2.1], "s"),
        ("Cellulose film", "#3a9d5d", [110, 9, 19, 41, 28, 4.3], "^"),
    ]
    n = len(axes_def)
    centre = 0.0
    # Equal angles: unequal spacing is supported by the model (each ray's
    # direction is measured, never inferred from a neighbour) but is NOT what real
    # figures look like, and an example should look like the thing it stands for.
    # Clockwise from 12 o'clock, which is how the app asks for the spokes.
    angles = [2.0 * np.pi * i / n for i in range(n)]
    R = 1.0  # unit radius; every axis is drawn to the same LENGTH, not the same scale

    def spoke_xy(i, value):
        frac = (value - centre) / (axes_def[i][1] - centre)
        return np.array([R * frac * np.sin(angles[i]), R * frac * np.cos(angles[i])])

    fig, ax = plt.subplots(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")

    # Grid rings at 20..100% of each axis, drawn as the polygon joining equal
    # FRACTIONS of the spokes -- which is what a real radar chart's web is.
    for frac in (0.2, 0.4, 0.6, 0.8, 1.0):
        ring = [np.array([R * frac * np.sin(a), R * frac * np.cos(a)]) for a in angles]
        ring.append(ring[0])
        pts = np.array(ring)
        ax.plot(pts[:, 0], pts[:, 1], color="#dcdcdc", lw=0.8, zorder=1)

    # The spokes themselves, plus per-axis tick labels so the ranges are READABLE
    # off the figure -- without them the per-axis scales would be invisible and the
    # example would not actually be digitizable.
    for i, (label, vmax) in enumerate(axes_def):
        end = np.array([R * np.sin(angles[i]), R * np.cos(angles[i])])
        ax.plot([0, end[0]], [0, end[1]], color="#9a9a9a", lw=1.0, zorder=1)
        # Tick labels are pushed PERPENDICULAR to their spoke, and carry a white
        # backing box: placed on the ray they sat under the data polygons, which is
        # the one thing an example figure must not do -- the numbers a user reads
        # to calibrate have to be legible against the series they are tracing.
        perp = np.array([np.cos(angles[i]), -np.sin(angles[i])])
        for frac in (0.5, 1.0):
            tick = np.array([R * frac * np.sin(angles[i]), R * frac * np.cos(angles[i])])
            pos = tick + perp * 0.06
            ax.text(pos[0], pos[1], f"{vmax * frac:g}",
                    ha="center", va="center", fontsize=8, color="#666666", zorder=4,
                    bbox=dict(facecolor="white", edgecolor="none", pad=0.8, alpha=0.85))
        lab = end * 1.22
        ax.text(lab[0], lab[1], label, ha="center", va="center",
                fontsize=10.5, color="#5a3a2a", fontweight="bold", zorder=4)

    for sname, colour, values, marker in series:
        pts = [spoke_xy(i, v) for i, v in enumerate(values)]
        pts.append(pts[0])
        arr = np.array(pts)
        ax.plot(arr[:, 0], arr[:, 1], color=colour, lw=2.0, zorder=3, label=sname)
        # ⚑ NO WHITE MARKER RIM (David, 2026-07-27). A white edge is a styling
        # choice, not what radar charts normally look like: real ones draw a
        # continuous line, or markers laid OVER it — not markers that cut it. And
        # the rim is not merely cosmetic here. It breaks the ink exactly where the
        # series crosses its axis, which is the one place the figure states a
        # number: reading outward along the ray gives line, white gap, marker,
        # i.e. one crossing that looks like two. An example should be the thing it
        # stands for, and this one was quietly the hardest case in the set.
        ax.plot(arr[:-1, 0], arr[:-1, 1], marker, color=colour, markersize=7,
                markeredgecolor=colour, markeredgewidth=1.0, zorder=4)

    ax.plot(0, 0, "o", color="#444444", markersize=4, zorder=5)
    # The centre's value, stated on the figure. The app asks for it once during
    # calibration (0 preselected), so an example that never shows it would be
    # asking the user for a number the figure had not told them.
    ax.text(-0.055, -0.055, "0", ha="right", va="top", fontsize=8.5, color="#444444", zorder=5)
    ax.set_title("Material Performance Profile — Biopolymer Films", fontsize=15, fontweight="bold")
    ax.set_xlim(-1.55, 1.55)
    ax.set_ylim(-1.42, 1.42)
    ax.set_aspect("equal")
    ax.axis("off")
    ax.legend(loc="lower right", fontsize=9, framealpha=0.9)
    fig.tight_layout()

    # Calibration anchors in IMAGE pixel space (origin top-left, y DOWN), same
    # conventions as _xy_calibration: the centre, then one known point per spoke at
    # that axis's maximum. Keys match the app's own step keys (origin, spoke1..N).
    fig.canvas.draw()
    h = fig.get_figheight() * fig.dpi
    w = fig.get_figwidth() * fig.dpi

    def anchor(dx, dy):
        sx, sy = ax.transData.transform((dx, dy))
        return {"px": round(float(sx), 2), "py": round(float(h - sy), 2)}

    anchors = {"origin": {**anchor(0.0, 0.0), "value": centre}}
    for i, (label, vmax) in enumerate(axes_def):
        end = spoke_xy(i, vmax)
        anchors[f"spoke{i + 1}"] = {**anchor(end[0], end[1]), "value": vmax, "name": label}

    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png",
                   "note": "Synthetic ground truth. Each axis has its OWN range and a shared centre of 0 — the per-axis-scale case the only prior art (ChartSense) excludes."},
        "graphType": "spider",
        "axes": [{"axis": i + 1, "name": label, "centre": centre, "max": vmax}
                 for i, (label, vmax) in enumerate(axes_def)],
        "calibration": {"imageWidth": round(w), "imageHeight": round(h), "anchors": anchors},
        "series": [
            {"name": sname,
             "points": [{"axis": i + 1, "name": axes_def[i][0], "value": v} for i, v in enumerate(values)]}
            for sname, _colour, values, _marker in series
        ],
    })


# --- Pie family (v1.6) -------------------------------------------------------
#
# Three figures rather than one, each isolating ONE capability, so a failing
# extraction points at a single thing:
#   1. a perfectly circular pie   -- the base case
#   2. a pie with one slice pulled out -- the own-apex capture
#   3. a donut, in real units with the total in the hole -- inner radius + a
#      total that is not 100
#
# ⚑ ALL THREE ARE DRAWN CLOCKWISE FROM 12 O'CLOCK (`startangle=90`,
# `counterclock=False`), which is how pies are conventionally read, and is stated
# here rather than left to matplotlib's default (0° = east, anticlockwise) so the
# truth's boundary angles are unambiguous.
#
# ⚑ The truth carries the SLICE VALUES as `{category, value}` -- the bar-shaped
# record -- because that is what the app stores and what a pie must be able to
# redraw as. The boundary PIXELS ride in the `calibration` block so an e2e can
# click the real figure rather than geometry it invented for itself.

def _pie_truth_geometry(fig, ax, values, *, radius=1.0, explode=None, start=90.0):
    """Centre, rim and every slice boundary in IMAGE pixel space (origin top-left,
    y DOWN) -- the space PlotTracer calibrates in.

    A boundary is emitted at the radius of the slice it bounds, and an EXPLODED
    slice's boundaries are measured about its own translated apex: pulling a slice
    out is a translation, so its arc keeps `radius` while the centre of that arc
    moves. Measuring it against the shared centre is what would misread it."""
    # ⚑ DRAW FIRST. `set_aspect("equal")` does not adjust the axes box until draw
    # time, so reading transData before then yields an ANISOTROPIC transform: the
    # figure renders as a circle while every anchor is computed on an ellipse. The
    # symptom was subtle and would have poisoned the ground truth -- distances from
    # centre to the recorded edges came out 258/282/320/329 px where all should be
    # 348, and the boundary angles drifted several degrees from the ones intended.
    # No other generator hits this because none of them constrain aspect.
    fig.canvas.draw()
    h = fig.get_figheight() * fig.dpi
    w = fig.get_figwidth() * fig.dpi

    def px(dx, dy):
        sx, sy = ax.transData.transform((dx, dy))
        return {"px": round(float(sx), 2), "py": round(float(h - sy), 2)}

    total = float(sum(values))
    explode = explode or [0.0] * len(values)
    # Boundary k sits at the cumulative fraction, going CLOCKWISE from `start`.
    cum = 0.0
    edges = []          # (angle_deg, index_of_slice_starting_here)
    for i, v in enumerate(values):
        edges.append((start - 360.0 * (cum / total), i))
        cum += v
    # ⚑ OUTLINE points are what the app actually calibrates from (v1.6): the centre is
    # FITTED through them rather than clicked, because a donut has no visible centre.
    # Four spread around the rim, so the truth exercises the least-squares path rather
    # than only the exact three-point case.
    outline = [px(radius * math.cos(math.radians(a)), radius * math.sin(math.radians(a)))
               for a in (90.0, 0.0, -90.0, 180.0)]
    # centre/rim are kept for reference and for the residual check; the app derives
    # both from `outline`.
    anchors = {"centre": px(0.0, 0.0), "rim": px(radius, 0.0), "outline": outline}
    slices = []
    for i, v in enumerate(values):
        a0 = edges[i][0]
        a1 = start - 360.0 * ((sum(values[: i + 1])) / total)
        mid = math.radians((a0 + a1) / 2.0)
        # An exploded slice's apex moves out along its own bisector.
        ax0, ay0 = explode[i] * math.cos(mid), explode[i] * math.sin(mid)
        slices.append({
            "index": i,
            "startAngle": round(a0, 4),
            "endAngle": round(a1, 4),
            "exploded": explode[i] > 0,
            "apex": px(ax0, ay0),
            "startEdge": px(ax0 + radius * math.cos(math.radians(a0)), ay0 + radius * math.sin(math.radians(a0))),
            "endEdge": px(ax0 + radius * math.cos(math.radians(a1)), ay0 + radius * math.sin(math.radians(a1))),
        })
    return {"imageWidth": round(w), "imageHeight": round(h), "anchors": anchors, "slices": slices}


PIE_COLOURS = ["#1f4e79", "#c0504d", "#4f9d3a", "#e0a458", "#7a5ba6", "#3aa8a0"]


def _pie_figure(title, labels, values, *, explode=None, donut=False, centre_text=None, fmt=None):
    fig = plt.figure(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax = fig.add_subplot()
    wedgeprops = dict(width=0.45, edgecolor="white") if donut else dict(edgecolor="white")
    ax.pie(
        values,
        labels=labels,
        explode=explode,
        colors=PIE_COLOURS[: len(values)],
        startangle=90,
        counterclock=False,
        autopct=fmt,
        pctdistance=0.75 if donut else 0.62,
        wedgeprops=wedgeprops,
        textprops=dict(fontsize=11),
    )
    if centre_text:
        ax.text(0, 0, centre_text, ha="center", va="center", fontsize=14, fontweight="bold")
    ax.set_aspect("equal")
    ax.set_title(title, fontsize=15)
    fig.tight_layout()
    return fig, ax


def gen_pie():
    """A perfectly circular pie — the base case. Percentages summing to 100, so the
    calibration's prefilled total of 100 is already correct and the slice values ARE
    the printed labels."""
    name = "pie-filler-composition"
    labels = ["Cellulose", "Lignin", "Hemicellulose", "Ash", "Extractives"]
    values = [42.0, 23.0, 18.0, 9.0, 8.0]  # sums to 100
    fig, ax = _pie_figure("Filler composition (%)", labels, values, fmt="%.0f%%")
    geom = _pie_truth_geometry(fig, ax, values)
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png",
                   "note": "Synthetic ground truth. A plain circular pie; the labels are percentages and sum to 100, so the total IS 100."},
        "graphType": "pie",
        "total": 100.0,
        "unit": "%",
        "sweep": 360,
        "calibration": geom,
        "series": [{"name": "Filler composition",
                    "points": [{"category": c, "value": v} for c, v in zip(labels, values)]}],
    })


def gen_pie_exploded():
    """A pie with ONE slice pulled out — the own-apex capture.

    ⚑ The exploded slice is TRANSLATED, so its arc keeps the pie's radius while that
    arc's centre moves out to the slice's own tip. Measured against the shared centre
    it misreads by roughly (d/r)·sin(half-angle) on EACH edge, and the two edges err
    in opposite directions, so a 90° slice pulled out by 10% of the radius reads about
    8° wrong. That is what this example exists to catch."""
    name = "pie-exploded-market-share"
    labels = ["PLA", "PHA", "Starch blend", "PBS", "Other"]
    values = [34.0, 27.0, 21.0, 11.0, 7.0]  # sums to 100
    explode = [0.0, 0.18, 0.0, 0.0, 0.0]    # PHA pulled out
    fig, ax = _pie_figure("Biopolymer film market share (%)", labels, values,
                          explode=explode, fmt="%.0f%%")
    geom = _pie_truth_geometry(fig, ax, values, explode=explode)
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png",
                   "note": "Synthetic ground truth. ONE slice (PHA) is pulled out by 0.18 of the radius; its boundaries must be measured about its own translated apex, not the shared centre."},
        "graphType": "pie",
        "total": 100.0,
        "unit": "%",
        "sweep": 360,
        "explodedCategory": "PHA",
        "calibration": geom,
        "series": [{"name": "Market share",
                    "points": [{"category": c, "value": v} for c, v in zip(labels, values)]}],
    })


def gen_donut():
    """A donut chart. About donuts. (David, and he is quite right.)

    The joke is free; the test value is not. This one carries two things the plain pie
    does not: an INNER RADIUS, which the angle is indifferent to — that indifference is
    exactly what lets one calibration read every ring — and a total that is NOT 100, so
    the calibration's prefilled default has to actually be changed to read the figure.
    The total is printed in the hole, which is where real donut charts put it (the
    Tableau example David found does the same with $2,297,201)."""
    name = "donut-donut-flavours"
    labels = ["Glazed", "Chocolate", "Boston cream", "Jelly", "Old-fashioned", "Maple bar"]
    values = [820.0, 610.0, 430.0, 290.0, 210.0, 140.0]  # sums to 2500
    total = float(sum(values))
    fig, ax = _pie_figure("Most popular donut flavours (thousands sold)", labels, values, donut=True,
                          centre_text=f"{total:,.0f}".replace(",", " ") + "\nthousand",
                          fmt=lambda p: f"{p * total / 100:,.0f}".replace(",", " "))
    geom = _pie_truth_geometry(fig, ax, values)
    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png",
                   "note": "Synthetic ground truth. A donut chart about donuts. Absolute units with the total printed in the hole — the total is 2500, NOT 100, so the calibration default must be changed to read it."},
        "graphType": "pie",
        "total": total,
        "unit": "thousands sold",
        "sweep": 360,
        "innerRadius": 0.55,
        "calibration": geom,
        "series": [{"name": "Donut flavours",
                    "points": [{"category": c, "value": v} for c, v in zip(labels, values)]}],
    })


def gen_pie_tilted():
    """A TILTED pie — the 2D stand-in for a 3D chart's top face.

    ⚑ Why this exists: about 12% of real pie figures in the PMC corpus are drawn in
    3D, and a 3D pie's top face is a COMPLETE, UNOCCLUDED ellipse — an exact affine
    image of the circle, so it is recoverable rather than refusable. Read flat, a 2:1
    figure turns a 7% slice into 13.4% while the readings still sum to 100, which is
    the silent-wrong-number shape this project exists to avoid.

    Drawn by squashing a circular pie to 55% of its height and rotating it, which is
    exactly what a projection does — so the truth here is the TRUE angles, and any
    reader that does not invert the map will disagree with them."""
    name = "pie-tilted-market-segments"
    labels = ["Segment A", "Segment B", "Segment C", "Segment D"]
    values = [45.0, 25.0, 20.0, 10.0]  # sums to 100
    squash, rot = 0.55, math.radians(18.0)

    fig = plt.figure(figsize=(9, 7), dpi=100)
    fig.patch.set_facecolor("white")
    ax = fig.add_subplot()
    ax.set_aspect("equal")
    ax.set_xlim(-1.4, 1.4)
    ax.set_ylim(-1.1, 1.1)
    ax.axis("off")

    def project(x, y):
        """Circle -> ellipse: squash in y, then rotate. An affine map, hence exactly
        invertible, which is the whole premise."""
        ys = y * squash
        return (x * math.cos(rot) - ys * math.sin(rot),
                x * math.sin(rot) + ys * math.cos(rot))

    total = float(sum(values))
    cum = 0.0
    for v, colour in zip(values, PIE_COLOURS):
        a0 = 90.0 - 360.0 * (cum / total)
        a1 = 90.0 - 360.0 * ((cum + v) / total)
        ts = np.linspace(math.radians(a0), math.radians(a1), 200)
        xy = [project(0.0, 0.0)] + [project(math.cos(t), math.sin(t)) for t in ts]
        ax.add_patch(plt.Polygon(xy, closed=True, facecolor=colour, edgecolor="white", linewidth=1.5))
        mid = math.radians((a0 + a1) / 2)
        lx, ly = project(0.62 * math.cos(mid), 0.62 * math.sin(mid))
        ax.text(lx, ly, f"{v:.0f}%", ha="center", va="center", color="white", fontsize=12, fontweight="bold")
        cum += v

    ax.set_title("Market segments (%) — drawn tilted", fontsize=15)
    fig.tight_layout()
    fig.canvas.draw()
    h = fig.get_figheight() * fig.dpi
    w = fig.get_figwidth() * fig.dpi

    def px(dx, dy):
        sx, sy = ax.transData.transform((dx, dy))
        return {"px": round(float(sx), 2), "py": round(float(h - sy), 2)}

    # Outline points on the ELLIPSE (a 3D pie's top-face rim). Eight, because five is
    # the bare minimum for an ellipse and a real user would place a few more.
    outline = [px(*project(math.cos(t), math.sin(t)))
               for t in [i / 8 * 2 * math.pi for i in range(8)]]
    slices = []
    cum = 0.0
    for i, v in enumerate(values):
        a0 = 90.0 - 360.0 * (cum / total)
        a1 = 90.0 - 360.0 * ((cum + v) / total)
        slices.append({
            "index": i,
            "startAngle": round(a0, 4),
            "endAngle": round(a1, 4),
            "exploded": False,
            "apex": px(*project(0.0, 0.0)),
            "startEdge": px(*project(math.cos(math.radians(a0)), math.sin(math.radians(a0)))),
            "endEdge": px(*project(math.cos(math.radians(a1)), math.sin(math.radians(a1)))),
        })
        cum += v

    _save(fig, name)
    _write_truth(name, {
        "source": {"imagePath": name + ".png",
                   "note": "Synthetic ground truth. A pie squashed to 55% height and rotated 18 degrees -- an AFFINE image of a circle, standing in for a 3D chart's top face. Reading it as a flat circle gives the wrong angles; inverting the map gives these."},
        "graphType": "pie",
        "total": 100.0,
        "unit": "%",
        "sweep": 360,
        "tilted": True,
        "projection": {"squash": squash, "rotationDeg": 18.0},
        "calibration": {"imageWidth": round(w), "imageHeight": round(h),
                        "anchors": {"centre": px(*project(0.0, 0.0)),
                                    "rim": px(*project(1.0, 0.0)),
                                    "outline": outline},
                        "slices": slices},
        "series": [{"name": "Market segments",
                    "points": [{"category": c, "value": v} for c, v in zip(labels, values)]}],
    })


if __name__ == "__main__":
    gen_scatter()
    gen_multiseries()
    gen_bar()
    gen_bar_grouped()
    gen_bar_stacked()
    gen_bar_floating()
    gen_histogram()
    gen_categorical()
    gen_stress_strain()
    gen_errorbar()
    gen_boxplot()
    gen_polar()
    gen_ccr()
    gen_dashstyles()
    gen_ternary()
    gen_map()
    gen_multipage_pdf()
    # ⚑ gen_spider used to sit BELOW this block and was therefore never called --
    # the one sample this file exists to make reproducible could not be regenerated
    # by the documented command. Found 2026-07-29 while adding the pie family.
    gen_spider()
    gen_pie()
    gen_pie_exploded()
    gen_donut()
    gen_pie_tilted()
    print("generated all 22 examples (+ .truth.json each): 11 PNG series types, ternary, map, multipage-pdf, spider, pie, exploded pie, donut, grouped bar, stacked bar, floating bar.")
