import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { readPng } from './helpers/readPng.js';
import { sampleColorBar, lookupColor, type ColorBarStrip } from '../../algorithms/colorBar.js';
import { samplePixelRgb } from '../../algorithms/samplePixel.js';
import type { RGB } from '../../algorithms/colorFilter.js';

/**
 * READING A COLOUR IS A LOOKUP, NOT AN ESTIMATE.
 *
 * ⚑⚑ DAVID, 2026-08-20, after seven days of arguing the point with me:
 * *"a lookup, not an estimator!"* and *"We do not INFER! We MEASURE!"*
 *
 * A heatmap is not drawn from a continuous ramp. It is generated by pushing
 * values through a COLORMAP - a lookup table of N discrete entries - and the key
 * beside it is that same table, printed. So the honest inverse is a lookup: is
 * this pixel's colour in the key, and where? Match, or no match.
 *
 * ⚑ MEASURED BEFORE IT WAS BUILT, on this repo's own fixtures:
 *
 *     heatmap-viridis.png   20/20 cell colours EXACTLY present in the key
 *     heatmap-jet.png       20/20 exactly present
 *     heatmap-jet-jpeg.png   2/20  - and the KEY itself is smeared,
 *                                    490 distinct colours where a colormap has 256
 *
 * On a clean figure the lookup succeeds forty times out of forty with no
 * tolerance at all. The projection-and-error-model it replaces bought nothing
 * there; it existed to manufacture an answer on a degraded figure, which is the
 * one thing this tool must not do.
 *
 * ⚑ THE TOLERANCE IS SET, NOT MODELLED. David: *"With some specific and set
 * degree of tolerance. Else everything real breaks down, because of fuzziness.
 * Like we have done for all other types of graphs."* So it is the same test
 * every other type already uses - Euclidean RGB distance against a declared
 * number (`colorFilter.ts`'s `dr² + dg² + db² <= tolerance²`), not a band
 * derived from the ramp's local behaviour.
 *
 * ⚑ AND THE RANGE IS WHAT IS MEASURABLE. David: *"it is the RANGE that
 * determines what is measurable and what is not."* The two known values only say
 * what a position is WORTH; they are interpolated along the range and may sit
 * anywhere on it. This function answers WHERE on the range, and nothing else.
 */

const DIR = './fixtures/colorbars';
const truth = JSON.parse(
  readFileSync(fileURLToPath(new URL(`${DIR}/truth.json`, import.meta.url)), 'utf8')
) as {
  figures: Array<{
    file: string;
    key: { from: { x: number; y: number }; to: { x: number; y: number } };
    cells: Array<{ x: number; y: number; value: number }>;
  }>;
};

function figure(file: string) {
  const fig = truth.figures.find((f) => f.file === file)!;
  const png = readPng(fileURLToPath(new URL(`${DIR}/${file}`, import.meta.url)));
  const image = { data: png.data, width: png.width, height: png.height };
  const r = sampleColorBar(image.data, image.width, image.height, fig.key.from, fig.key.to);
  expect(r.reason).toBeNull();
  return { fig, image, strip: r.strip! };
}

/** A key built as pixels: dark in the middle, light at both ends, so one grey
 * genuinely sits at two places. Not a real colormap - a real one is injective -
 * but the only way to reach the two-matches branch on purpose. */
function twoPlaceStrip(): ColorBarStrip {
  const W = 201;
  const H = 21;
  const data = new Uint8ClampedArray(W * H * 4);
  for (let y = 0; y < H; y++)
    for (let x = 0; x < W; x++) {
      const v = Math.round((Math.abs(x - (W - 1) / 2) / ((W - 1) / 2)) * 255);
      const i = (y * W + x) * 4;
      data[i] = v;
      data[i + 1] = v;
      data[i + 2] = v;
      data[i + 3] = 255;
    }
  const r = sampleColorBar(data, W, H, { x: 0, y: 10 }, { x: W - 1, y: 10 });
  expect(r.reason).toBeNull();
  return r.strip!;
}

const TOL = 8;

describe('looking a colour up in the key', () => {
  it('⚑⚑ every cell of a clean figure is FOUND - the lookup needs no help', () => {
    for (const file of ['heatmap-viridis.png', 'heatmap-jet.png']) {
      const { fig, image, strip } = figure(file);
      const found = fig.cells.filter((c) => lookupColor(strip, samplePixelRgb(image, c.x, c.y), TOL) !== null);
      expect(found, `${file}: every cell colour is in its own key`).toHaveLength(fig.cells.length);
    }
  });

  it('⚑⚑ a colour that is NOT on the range is not measurable, and says so by answering null', () => {
    const { strip } = figure('heatmap-viridis.png');
    // White paper, off any viridis key. Measured 219 away from the ramp - the
    // old projection handed back a confident position for it anyway.
    expect(lookupColor(strip, [255, 255, 255] as RGB, TOL)).toBeNull();
  });

  it('⚑ a colour is looked up where the KEY puts it, within about a step', () => {
    // The lookup has to land where the colour actually is, not merely somewhere.
    const { strip } = figure('heatmap-viridis.png');
    const mid = strip.samples[Math.floor(strip.samples.length / 2)]!;
    const t = lookupColor(strip, mid.rgb, TOL);
    expect(t).not.toBeNull();
    expect(Math.abs(t! - mid.t)).toBeLessThan(0.02);
  });

  it('⚑⚑ a colour that occupies a RUN of the key reads at the run’s MIDDLE', () => {
    // ⚠️ Not its first index. A colormap is a lookup table, so a key drawn 550px
    // long repeats each entry over about two pixels, and taking the first tied
    // position biases every reading to the low end of its plateau. Measured on
    // the jet fixture when this was found: a systematic 0.6-0.8 degree under-read
    // across a 160 degree range, in the same direction for every cell, from
    // colours that matched the key EXACTLY. A constant signed bias is the worst
    // kind, because averaging cells does not remove it.
    const { strip } = figure('heatmap-jet.png');
    const s = strip.samples;
    // Find a colour that occupies more than one sample.
    const idx = s.findIndex((sample, i) => i > 0 && i < s.length - 1 &&
      sample.rgb[0] === s[i + 1]!.rgb[0] && sample.rgb[1] === s[i + 1]!.rgb[1] && sample.rgb[2] === s[i + 1]!.rgb[2]);
    expect(idx, 'the fixture has a plateau to test').toBeGreaterThan(-1);
    let lo = idx;
    let hi = idx;
    const same = (a: RGB, b: RGB) => a[0] === b[0] && a[1] === b[1] && a[2] === b[2];
    while (lo > 0 && same(s[lo - 1]!.rgb, s[idx]!.rgb)) lo--;
    while (hi < s.length - 1 && same(s[hi + 1]!.rgb, s[idx]!.rgb)) hi++;
    const middle = (s[lo]!.t + s[hi]!.t) / 2;
    // Exact lookup only, so the run is the whole answer and nothing widens it.
    expect(lookupColor(strip, s[idx]!.rgb, 0)).toBeCloseTo(middle, 6);
  });

  it('⚑⚑ a colour the range holds in TWO separate places is not measurable either', () => {
    // A published colormap is injective, so this cannot arise from a clean read
    // - it means the scan, the compression or the sampling has degraded the
    // colour until it no longer identifies one position. Either way there is no
    // single answer, so there is no value.
    const strip = twoPlaceStrip();
    expect(lookupColor(strip, [128, 128, 128] as RGB, TOL)).toBeNull();
  });

  it('⚑ ...while a colour that key holds in ONE place still reads - no over-reach', () => {
    const strip = twoPlaceStrip();
    // Black sits only at the centre of this light-dark-light key.
    expect(lookupColor(strip, [0, 0, 0] as RGB, TOL)).not.toBeNull();
  });

  it('⚑ the tolerance is the knob, and it is the one that decides', () => {
    const { strip } = figure('heatmap-viridis.png');
    const mid = strip.samples[Math.floor(strip.samples.length / 2)]!.rgb;
    const nudged: RGB = [mid[0] + 6, mid[1], mid[2]];
    expect(lookupColor(strip, nudged, 0)).toBeNull(); // exact match only
    expect(lookupColor(strip, nudged, 8)).not.toBeNull(); // within a set tolerance
  });
});
